
package ch.xwr.seicentobilling.ui.tablet;

import com.vaadin.annotations.Push;
import com.vaadin.annotations.Theme;
import com.vaadin.server.VaadinRequest;
import com.vaadin.shared.communication.PushMode;
import com.vaadin.shared.ui.ui.Transport;
import com.xdev.security.authentication.ui.XdevAuthenticationNavigator;
import com.xdev.ui.XdevUI;

import ch.xwr.seicentobilling.ui.phone.AddressSearchView;
import ch.xwr.seicentobilling.ui.phone.ExpenseListView;
import ch.xwr.seicentobilling.ui.phone.ExpenseView;
import ch.xwr.seicentobilling.ui.phone.PeriodeView;
import ch.xwr.seicentobilling.ui.phone.ProjectLineListView;

@Push(value = PushMode.MANUAL, transport = Transport.LONG_POLLING)
@Theme("SeicentoBilling")
public class TabletUI extends XdevUI {
	public TabletUI() {
		super();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void init(final VaadinRequest request) {
		this.initUI();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.navigator = new XdevAuthenticationNavigator(this, this);

		this.navigator.setRedirectViewName("home");
		this.navigator.addView("", AuthView.class);
		this.navigator.addView("home", ch.xwr.seicentobilling.ui.desktop.MainView.class);
		this.navigator.addView("periodeView", PeriodeView.class);
		this.navigator.addView("projectLineListView", ProjectLineListView.class);
		this.navigator.addView("expenseView", ExpenseView.class);
		this.navigator.addView("expenseListView", ExpenseListView.class);
		this.navigator.addView("addressSearchView", AddressSearchView.class);

		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private XdevAuthenticationNavigator navigator;
	// </generated-code>
}