
package ch.xwr.seicentobilling.dal;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;

import com.xdev.dal.JPADAO;

import ch.xwr.seicentobilling.entities.Customer;
import ch.xwr.seicentobilling.entities.CustomerLink;
import ch.xwr.seicentobilling.entities.CustomerLink_;

/**
 * Home object for domain model class Bank.
 *
 * @see Acitivity
 */
public class CustomerLinkDAO extends JPADAO<CustomerLink, Long> {
	public CustomerLinkDAO() {
		super(CustomerLink.class);
	}

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<CustomerLink> findByCustomer(final Customer dao) {
		final EntityManager entityManager = em();

		final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();

		final ParameterExpression<Customer> daoParameter = criteriaBuilder.parameter(Customer.class, "dao");

		final CriteriaQuery<CustomerLink> criteriaQuery = criteriaBuilder.createQuery(CustomerLink.class);

		final Root<CustomerLink> root = criteriaQuery.from(CustomerLink.class);

		criteriaQuery.where(criteriaBuilder.equal(root.get(CustomerLink_.customer), daoParameter));

		criteriaQuery.orderBy(criteriaBuilder.desc(root.get(CustomerLink_.cnkValidFrom)));

		final TypedQuery<CustomerLink> query = entityManager.createQuery(criteriaQuery);
		query.setParameter(daoParameter, dao);
		return query.getResultList();
	}
}