
package ch.xwr.seicentobilling.dal;

import java.util.Iterator;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;

import com.xdev.dal.JPADAO;

import ch.xwr.seicentobilling.entities.CostAccount;
import ch.xwr.seicentobilling.entities.ExpenseTemplate;
import ch.xwr.seicentobilling.entities.ExpenseTemplate_;
import ch.xwr.seicentobilling.entities.ProjectLine;

/**
 * Home object for domain model class ProjectLine.
 *
 * @see ProjectLine
 */
public class ExpenseTemplateDAO extends JPADAO<ExpenseTemplate, Long> {

	public ExpenseTemplateDAO() {
		super(ExpenseTemplate.class);
	}


	public ExpenseTemplate findByKeyNumber(final CostAccount csaDao, final int keynumber){
		ExpenseTemplate retObj = null;

		final List<ExpenseTemplate> lst = findByCostAccount(csaDao);
		for (final Iterator<ExpenseTemplate> iterator = lst.iterator(); iterator.hasNext();) {
			final ExpenseTemplate template = iterator.next();

			if (template.getExtKeyNumber() == keynumber) {
				retObj = template;
				break;
			}
		}

		return retObj;
	}


	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<ExpenseTemplate> findByCostAccount(final CostAccount dao) {
		final EntityManager entityManager = em();

		final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();

		final ParameterExpression<CostAccount> daoParameter = criteriaBuilder.parameter(CostAccount.class, "dao");

		final CriteriaQuery<ExpenseTemplate> criteriaQuery = criteriaBuilder.createQuery(ExpenseTemplate.class);

		final Root<ExpenseTemplate> root = criteriaQuery.from(ExpenseTemplate.class);

		criteriaQuery.where(criteriaBuilder.equal(root.get(ExpenseTemplate_.costAccount), daoParameter));

		criteriaQuery.orderBy(criteriaBuilder.asc(root.get(ExpenseTemplate_.extKeyNumber)));

		final TypedQuery<ExpenseTemplate> query = entityManager.createQuery(criteriaQuery);
		query.setParameter(daoParameter, dao);
		return query.getResultList();

	}

}