
package ch.xwr.seicentobilling.dal;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;

import com.xdev.dal.JPADAO;

import ch.xwr.seicentobilling.entities.Order;
import ch.xwr.seicentobilling.entities.OrderLine;
import ch.xwr.seicentobilling.entities.OrderLine_;

/**
 * Home object for domain model class OrderLine.
 *
 * @see OrderLine
 */
public class OrderLineDAO extends JPADAO<OrderLine, Long> {
	public OrderLineDAO() {
		super(OrderLine.class);
	}

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<OrderLine> findByOrder(final Order dao) {
		final EntityManager entityManager = em();

		final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();

		final ParameterExpression<Order> daoParameter = criteriaBuilder.parameter(Order.class, "dao");

		final CriteriaQuery<OrderLine> criteriaQuery = criteriaBuilder.createQuery(OrderLine.class);

		final Root<OrderLine> root = criteriaQuery.from(OrderLine.class);

		criteriaQuery.where(criteriaBuilder.equal(root.get(OrderLine_.orderhdr), daoParameter));

		criteriaQuery.orderBy(criteriaBuilder.asc(root.get(OrderLine_.odlNumber)));

		final TypedQuery<OrderLine> query = entityManager.createQuery(criteriaQuery);
		query.setParameter(daoParameter, dao);
		return query.getResultList();
	}
}