
package ch.xwr.seicentobilling.dal;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;

import com.xdev.dal.JPADAO;

import ch.xwr.seicentobilling.entities.CostAccount;
import ch.xwr.seicentobilling.entities.Periode;
import ch.xwr.seicentobilling.entities.Periode_;

/**
 * Home object for domain model class Periode.
 *
 * @see Periode
 */
public class PeriodeDAO extends JPADAO<Periode, Long> {
	public PeriodeDAO() {
		super(Periode.class);
	}

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<Periode> findByCostAccount(final CostAccount costaccount) {
		final EntityManager entityManager = em();

		final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();

		final ParameterExpression<CostAccount> costaccountParameter = criteriaBuilder.parameter(CostAccount.class,
				"costaccount");

		final CriteriaQuery<Periode> criteriaQuery = criteriaBuilder.createQuery(Periode.class);

		final Root<Periode> root = criteriaQuery.from(Periode.class);

		criteriaQuery.where(criteriaBuilder.equal(root.get(Periode_.costAccount), costaccountParameter));

		criteriaQuery.orderBy(criteriaBuilder.desc(root.get(Periode_.perYear)),
				criteriaBuilder.desc(root.get(Periode_.perMonth)));

		final TypedQuery<Periode> query = entityManager.createQuery(criteriaQuery);
		query.setParameter(costaccountParameter, costaccount);
		return query.getResultList();
	}
}