
package ch.xwr.seicentobilling.dal;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;

import com.xdev.dal.JPADAO;

import ch.xwr.seicentobilling.entities.CostAccount;
import ch.xwr.seicentobilling.entities.Project;
import ch.xwr.seicentobilling.entities.ResPlanning;
import ch.xwr.seicentobilling.entities.ResPlanning_;

/**
 * Home object for domain model class ResPlanning.
 *
 * @see ResPlanning
 */
public class ResPlanningDAO extends JPADAO<ResPlanning, Long> {
	public ResPlanningDAO() {
		super(ResPlanning.class);
	}

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<ResPlanning> findByProjectAndCostAccount(final Project project, final CostAccount costaccount) {
		final EntityManager entityManager = em();

		final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();

		final ParameterExpression<Project> projectParameter = criteriaBuilder.parameter(Project.class, "project");
		final ParameterExpression<CostAccount> costaccountParameter = criteriaBuilder.parameter(CostAccount.class,
				"costaccount");

		final CriteriaQuery<ResPlanning> criteriaQuery = criteriaBuilder.createQuery(ResPlanning.class);

		final Root<ResPlanning> root = criteriaQuery.from(ResPlanning.class);

		criteriaQuery.where(criteriaBuilder.and(criteriaBuilder.equal(root.get(ResPlanning_.project), projectParameter),
				criteriaBuilder.equal(root.get(ResPlanning_.costAccount), costaccountParameter)));

		criteriaQuery.orderBy(criteriaBuilder.desc(root.get(ResPlanning_.rspPlandate)));

		final TypedQuery<ResPlanning> query = entityManager.createQuery(criteriaQuery);
		query.setParameter(projectParameter, project);
		query.setParameter(costaccountParameter, costaccount);
		return query.getResultList();
	}
}