
package ch.xwr.seicentobilling.dal;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;

import com.xdev.dal.JPADAO;

import ch.xwr.seicentobilling.entities.Vat;
import ch.xwr.seicentobilling.entities.VatLine;
import ch.xwr.seicentobilling.entities.VatLine_;

/**
 * Home object for domain model class Vat.
 *
 * @see Vat
 */
public class VatLineDAO extends JPADAO<VatLine, Long> {
	public VatLineDAO() {
		super(VatLine.class);
	}

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<VatLine> findByVat(final Vat vat) {
		final EntityManager entityManager = em();

		final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();

		final ParameterExpression<Vat> vatParameter = criteriaBuilder.parameter(Vat.class, "vat");

		final CriteriaQuery<VatLine> criteriaQuery = criteriaBuilder.createQuery(VatLine.class);

		final Root<VatLine> root = criteriaQuery.from(VatLine.class);

		criteriaQuery.where(criteriaBuilder.equal(root.get(VatLine_.vat), vatParameter));

		criteriaQuery.orderBy(criteriaBuilder.desc(root.get(VatLine_.vanValidFrom)));

		final TypedQuery<VatLine> query = entityManager.createQuery(criteriaQuery);
		query.setParameter(vatParameter, vat);
		return query.getResultList();
	}
}