package ch.xwr.seicentobilling.ui.desktop;

import java.util.Calendar;
import java.util.Locale;

import com.vaadin.server.ClientConnector;
import com.vaadin.server.FontAwesome;
import com.vaadin.server.VaadinSession;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.UI;
import com.xdev.security.authorization.Subject;
import com.xdev.server.aa.openid.auth.AzureUser;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevTabSheet;
import com.xdev.ui.XdevVerticalLayout;
import com.xdev.ui.XdevView;

import ch.xwr.seicentobilling.business.Seicento;
import ch.xwr.seicentobilling.business.TheVersion;
import ch.xwr.seicentobilling.business.auth.SeicentoUser;

public class ApplicationSettingsTabView extends XdevView {

	private SeicentoUser currentUser;
	private Integer index;

	/**
	 *
	 */
	public ApplicationSettingsTabView() {
		super();
		this.initUI();

		final TheVersion ver = new TheVersion();
		this.labelVersion.setValue(ver.getEntryById("version"));
		this.labelArtifact.setValue(ver.getEntryById("groupId") + " " + ver.getEntryById("artifactId") );

	}

	/**
	 * Event handler delegate method for the {@link XdevGridLayout}
	 * {@link #gridLayoutUsr}.
	 *
	 * @see ClientConnector.AttachListener#attach(ClientConnector.AttachEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void gridLayoutUsr_attach(final ClientConnector.AttachEvent event) {
		final Subject sub = VaadinSession.getCurrent().getAttribute(Subject.class);

		if (sub != null && sub instanceof AzureUser)
		{
			this.currentUser = new SeicentoUser();
			this.currentUser.setAzureUser((AzureUser) sub);
			showInfos();
		} else if (sub != null && sub instanceof SeicentoUser){
			this.currentUser = (SeicentoUser) sub;
			showInfos();
		}
	}

	private void showInfos() {
		if (this.currentUser != null && this.currentUser.getClaimSet().getClaims() != null)
		{
			this.index = 0;
			final XdevGridLayout newGrid = new XdevGridLayout();
			this.currentUser.getClaimSet().getClaims().forEach((k,v) -> {
				newGrid.addComponent(new Label(k), 0, this.index);
				newGrid.addComponent(new Label(v.toString()), 1, this.index);
				this.index++;
			});
			this.gridLayoutUsr.addComponent(newGrid);
		}
	}

	/**
	 * Event handler delegate method for the {@link XdevGridLayout}
	 * {@link #gridLayoutStats}.
	 *
	 * @see ClientConnector.AttachListener#attach(ClientConnector.AttachEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void gridLayoutStats_attach(final ClientConnector.AttachEvent event) {
		this.lblMemory.setValue("" + Seicento.getMemory());
		this.lblSession.setValue(UI.getCurrent().getSession().getState().name());
		this.lblJava.setValue(System.getProperty("java.version"));

	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdThemeSeicento}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdThemeSeicento_buttonClick(final Button.ClickEvent event) {
		this.getUI().setTheme("SeicentoBilling");
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdThemeFb}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdThemeFb_buttonClick(final Button.ClickEvent event) {
		this.getUI().setTheme("Facebook");

	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdThemeDark}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdThemeDark_buttonClick(final Button.ClickEvent event) {
		this.getUI().setTheme("Darksb");
	}

	/**
	 * Event handler delegate method for the {@link XdevGridLayout}
	 * {@link #gridLayoutApp}.
	 *
	 * @see ClientConnector.AttachListener#attach(ClientConnector.AttachEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void gridLayoutApp_attach(final ClientConnector.AttachEvent event) {
		final Locale currentLocale = Locale.getDefault();
		this.labelCountry.setValue(currentLocale.getDisplayCountry());
		this.labelLanguage.setValue(currentLocale.getDisplayLanguage());

		final Calendar cal = Calendar.getInstance();
		this.labelTimeZone.setValue(cal.getTimeZone().getID());

		this.labelUsername.setValue(Seicento.getUserName());

	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.verticalLayout = new XdevVerticalLayout();
		this.tabSheet = new XdevTabSheet();
		this.gridLayoutApp = new XdevGridLayout();
		this.label5 = new XdevLabel();
		this.labelUsername = new XdevLabel();
		this.label = new XdevLabel();
		this.labelCountry = new XdevLabel();
		this.label2 = new XdevLabel();
		this.labelLanguage = new XdevLabel();
		this.label3 = new XdevLabel();
		this.labelTimeZone = new XdevLabel();
		this.label4 = new XdevLabel();
		this.labelVersion = new XdevLabel();
		this.labelArtifact = new XdevLabel();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.cmdThemeDark = new XdevButton();
		this.cmdThemeFb = new XdevButton();
		this.cmdThemeSeicento = new XdevButton();
		this.gridLayoutUsr = new XdevGridLayout();
		this.gridLayoutStats = new XdevGridLayout();
		this.label6 = new XdevLabel();
		this.lblMemory = new XdevLabel();
		this.label7 = new XdevLabel();
		this.lblSession = new XdevLabel();
		this.label8 = new XdevLabel();
		this.lblJava = new XdevLabel();

		this.verticalLayout.setMargin(new MarginInfo(false));
		this.tabSheet.setStyleName("framed");
		this.gridLayoutApp.setMargin(new MarginInfo(true, true, false, true));
		this.label5.setValue("Name");
		this.labelUsername.setValue("unknown");
		this.label.setValue("Country");
		this.labelCountry.setValue("CH");
		this.label2.setValue("Language");
		this.labelLanguage.setValue("German");
		this.label3.setValue("Time Zone");
		this.labelTimeZone.setValue("unknown");
		this.label4.setValue("Version");
		this.labelVersion.setValue("0.6");
		this.labelArtifact.setValue("0.6");
		this.horizontalLayout.setIcon(FontAwesome.DASHBOARD);
		this.horizontalLayout.setCaption("Theme's");
		this.horizontalLayout.setStyleName("resize-button-caption");
		this.horizontalLayout.setMargin(new MarginInfo(false, false, true, false));
		this.cmdThemeDark.setCaption("Dark");
		this.cmdThemeFb.setCaption("Facebook");
		this.cmdThemeSeicento.setCaption("Reset");
		this.gridLayoutUsr.setMargin(new MarginInfo(true, true, false, true));
		this.label6.setValue("Memory used MB");
		this.lblMemory.setValue("Version");
		this.label7.setValue("Session");
		this.lblSession.setValue("Version");
		this.label8.setValue("Java");
		this.lblJava.setValue("Java");

		this.cmdThemeDark.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdThemeDark);
		this.horizontalLayout.setComponentAlignment(this.cmdThemeDark, Alignment.MIDDLE_CENTER);
		this.cmdThemeFb.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdThemeFb);
		this.horizontalLayout.setComponentAlignment(this.cmdThemeFb, Alignment.MIDDLE_CENTER);
		this.cmdThemeSeicento.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdThemeSeicento);
		this.horizontalLayout.setComponentAlignment(this.cmdThemeSeicento, Alignment.MIDDLE_CENTER);
		final CustomComponent horizontalLayout_spacer = new CustomComponent();
		horizontalLayout_spacer.setSizeFull();
		this.horizontalLayout.addComponent(horizontalLayout_spacer);
		this.horizontalLayout.setExpandRatio(horizontalLayout_spacer, 1.0F);
		this.gridLayoutApp.setColumns(2);
		this.gridLayoutApp.setRows(8);
		this.label5.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.label5, 0, 0);
		this.labelUsername.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.labelUsername, 1, 0);
		this.label.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.label, 0, 1);
		this.labelCountry.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.labelCountry, 1, 1);
		this.label2.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.label2, 0, 2);
		this.labelLanguage.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.labelLanguage, 1, 2);
		this.label3.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.label3, 0, 3);
		this.labelTimeZone.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.labelTimeZone, 1, 3);
		this.label4.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.label4, 0, 4);
		this.labelVersion.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.labelVersion, 1, 4);
		this.labelArtifact.setSizeUndefined();
		this.gridLayoutApp.addComponent(this.labelArtifact, 1, 5);
		this.horizontalLayout.setWidth(100, Unit.PERCENTAGE);
		this.horizontalLayout.setHeight(100, Unit.PIXELS);
		this.gridLayoutApp.addComponent(this.horizontalLayout, 0, 6, 1, 6);
		this.gridLayoutApp.setColumnExpandRatio(0, 10.0F);
		this.gridLayoutApp.setColumnExpandRatio(1, 40.0F);
		final CustomComponent gridLayoutApp_vSpacer = new CustomComponent();
		gridLayoutApp_vSpacer.setSizeFull();
		this.gridLayoutApp.addComponent(gridLayoutApp_vSpacer, 0, 7, 1, 7);
		this.gridLayoutApp.setRowExpandRatio(7, 1.0F);
		this.gridLayoutStats.setColumns(3);
		this.gridLayoutStats.setRows(4);
		this.label6.setSizeUndefined();
		this.gridLayoutStats.addComponent(this.label6, 0, 0);
		this.lblMemory.setSizeUndefined();
		this.gridLayoutStats.addComponent(this.lblMemory, 1, 0);
		this.label7.setSizeUndefined();
		this.gridLayoutStats.addComponent(this.label7, 0, 1);
		this.lblSession.setSizeUndefined();
		this.gridLayoutStats.addComponent(this.lblSession, 1, 1);
		this.label8.setSizeUndefined();
		this.gridLayoutStats.addComponent(this.label8, 0, 2);
		this.lblJava.setSizeUndefined();
		this.gridLayoutStats.addComponent(this.lblJava, 1, 2);
		final CustomComponent gridLayoutStats_hSpacer = new CustomComponent();
		gridLayoutStats_hSpacer.setSizeFull();
		this.gridLayoutStats.addComponent(gridLayoutStats_hSpacer, 2, 0, 2, 2);
		this.gridLayoutStats.setColumnExpandRatio(2, 1.0F);
		final CustomComponent gridLayoutStats_vSpacer = new CustomComponent();
		gridLayoutStats_vSpacer.setSizeFull();
		this.gridLayoutStats.addComponent(gridLayoutStats_vSpacer, 0, 3, 1, 3);
		this.gridLayoutStats.setRowExpandRatio(3, 1.0F);
		this.gridLayoutApp.setSizeFull();
		this.tabSheet.addTab(this.gridLayoutApp, "Application", null);
		this.gridLayoutUsr.setSizeFull();
		this.tabSheet.addTab(this.gridLayoutUsr, "UserInfo", null);
		this.gridLayoutStats.setSizeFull();
		this.tabSheet.addTab(this.gridLayoutStats, "Statistics", null);
		this.tabSheet.setSelectedTab(this.gridLayoutApp);
		this.tabSheet.setSizeFull();
		this.verticalLayout.addComponent(this.tabSheet);
		this.verticalLayout.setComponentAlignment(this.tabSheet, Alignment.MIDDLE_CENTER);
		this.verticalLayout.setExpandRatio(this.tabSheet, 10.0F);
		this.verticalLayout.setSizeFull();
		this.setContent(this.verticalLayout);
		this.setSizeFull();

		this.gridLayoutApp.addAttachListener(event -> this.gridLayoutApp_attach(event));
		this.cmdThemeDark.addClickListener(event -> this.cmdThemeDark_buttonClick(event));
		this.cmdThemeFb.addClickListener(event -> this.cmdThemeFb_buttonClick(event));
		this.cmdThemeSeicento.addClickListener(event -> this.cmdThemeSeicento_buttonClick(event));
		this.gridLayoutUsr.addAttachListener(event -> this.gridLayoutUsr_attach(event));
		this.gridLayoutStats.addAttachListener(event -> this.gridLayoutStats_attach(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel label5, labelUsername, label, labelCountry, label2, labelLanguage, label3, labelTimeZone, label4,
			labelVersion, labelArtifact, label6, lblMemory, label7, lblSession, label8, lblJava;
	private XdevButton cmdThemeSeicento, cmdThemeDark, cmdThemeFb;
	private XdevHorizontalLayout horizontalLayout;
	private XdevTabSheet tabSheet;
	private XdevGridLayout gridLayoutApp, gridLayoutUsr, gridLayoutStats;
	private XdevVerticalLayout verticalLayout;
	// </generated-code>

}
