
package ch.xwr.seicentobilling.ui.desktop;

import com.vaadin.event.ShortcutAction;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Notification;
import com.xdev.security.authentication.AuthenticationFailedException;
import com.xdev.security.authentication.CredentialsUsernamePassword;
import com.xdev.security.authentication.ui.Authentication;
import com.xdev.server.aa.openid.azure.AzurePopupConfig;
import com.xdev.server.aa.openid.ui.AzureOauthPopupButton;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevPanel;
import com.xdev.ui.XdevPasswordField;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevView;

import ch.xwr.seicentobilling.business.Seicento;
import ch.xwr.seicentobilling.business.auth.AzureHelper;
import ch.xwr.seicentobilling.business.auth.DbAuthenticationProvider;
import ch.xwr.seicentobilling.business.auth.SeicentoUser;

public class AuthView extends XdevView implements com.xdev.security.authentication.ui.LoginView {

	private AzureOauthPopupButton azureLoginButton = null;

	/**
	 *
	 */
	public AuthView() {
		super();
		this.initUI();

		final String lm = Seicento.getLoginMethod();
		if (lm.equalsIgnoreCase("azure")) {
			enableOauth();
		} else {
			enableLocal();
		}
	}

	private void enableLocal() {
		this.gridLayout.replaceComponent(this.panelMain, this.panelLocal);

		this.panelLocal.setVisible(true);
		this.panelOauth.setVisible(false);
	}

	private void enableOauth() {
		// NP String xx = this.getParent().getUI().getPage().getLocation().toString();
		final AzureHelper hlp = new AzureHelper();
		final AzurePopupConfig config = hlp.getAzureConfig();
		this.azureLoginButton =  new AzureOauthPopupButton(config, true);

		this.gridLayout2.replaceComponent(this.cmdLogin, this.azureLoginButton);
		this.gridLayout.replaceComponent(this.panelMain, this.panelOauth);

		this.panelLocal.setVisible(false);
		this.panelOauth.setVisible(true);
	}

	@Override
	public String getPassword() {
		return this.txtPassword.getValue();
	}

	@Override
	public String getUsername() {
		return this.txtUsername.getValue();
	}


	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdLoginLocal}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdLoginLocal_buttonClick(final Button.ClickEvent event) {
		try {
			final CredentialsUsernamePassword credentials = CredentialsUsernamePassword.New(getUsername(), getPassword());
			final DbAuthenticationProvider authenticatorProvider = DbAuthenticationProvider.getInstance();
			final Object authenticationResult = authenticatorProvider.provideAuthenticator().authenticate(credentials);
			//Authentication.login(new Subject.Implementation(credentials.username()), authenticationResult);

			Authentication.login(new SeicentoUser(credentials.username()), authenticationResult);

		} catch (final AuthenticationFailedException e) {
			Notification.show("Invalid username/password");
		}
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.panelMain = new XdevPanel();
		this.gridLayout4 = new XdevGridLayout();
		this.panelOauth = new XdevPanel();
		this.gridLayout2 = new XdevGridLayout();
		this.cmdLogin = new XdevButton();
		this.panelLocal = new XdevPanel();
		this.gridLayout3 = new XdevGridLayout();
		this.txtUsername = new XdevTextField();
		this.txtPassword = new XdevPasswordField();
		this.cmdLoginLocal = new XdevButton();

		this.panelMain.setCaption("Login");
		this.panelMain.setTabIndex(0);
		this.panelMain.setVisible(false);
		this.panelOauth.setCaption("Login");
		this.panelOauth.setTabIndex(0);
		this.panelOauth.setVisible(false);
		this.cmdLogin.setCaption("Login");
		this.cmdLogin.setStyleName("friendly");
		this.cmdLogin.setClickShortcut(ShortcutAction.KeyCode.ENTER);
		this.panelLocal.setCaption("Login");
		this.panelLocal.setTabIndex(0);
		this.panelLocal.setVisible(false);
		this.txtUsername.setCaption("Username");
		this.txtPassword.setCaption("Password");
		this.cmdLoginLocal.setCaption("Login");
		this.cmdLoginLocal.setStyleName("friendly");
		this.cmdLoginLocal.setClickShortcut(ShortcutAction.KeyCode.ENTER);

		this.gridLayout4.setSizeFull();
		this.panelMain.setContent(this.gridLayout4);
		this.gridLayout2.setColumns(1);
		this.gridLayout2.setRows(2);
		this.cmdLogin.setSizeUndefined();
		this.gridLayout2.addComponent(this.cmdLogin, 0, 0);
		this.gridLayout2.setComponentAlignment(this.cmdLogin, Alignment.MIDDLE_RIGHT);
		this.gridLayout2.setColumnExpandRatio(0, 10.0F);
		final CustomComponent gridLayout2_vSpacer = new CustomComponent();
		gridLayout2_vSpacer.setSizeFull();
		this.gridLayout2.addComponent(gridLayout2_vSpacer, 0, 1, 0, 1);
		this.gridLayout2.setRowExpandRatio(1, 1.0F);
		this.gridLayout2.setSizeFull();
		this.panelOauth.setContent(this.gridLayout2);
		this.gridLayout3.setColumns(1);
		this.gridLayout3.setRows(4);
		this.txtUsername.setSizeUndefined();
		this.gridLayout3.addComponent(this.txtUsername, 0, 0);
		this.txtPassword.setSizeUndefined();
		this.gridLayout3.addComponent(this.txtPassword, 0, 1);
		this.cmdLoginLocal.setSizeUndefined();
		this.gridLayout3.addComponent(this.cmdLoginLocal, 0, 2);
		this.gridLayout3.setComponentAlignment(this.cmdLoginLocal, Alignment.MIDDLE_RIGHT);
		this.gridLayout3.setColumnExpandRatio(0, 10.0F);
		final CustomComponent gridLayout3_vSpacer = new CustomComponent();
		gridLayout3_vSpacer.setSizeFull();
		this.gridLayout3.addComponent(gridLayout3_vSpacer, 0, 3, 0, 3);
		this.gridLayout3.setRowExpandRatio(3, 1.0F);
		this.gridLayout3.setSizeFull();
		this.panelLocal.setContent(this.gridLayout3);
		this.gridLayout.setColumns(2);
		this.gridLayout.setRows(2);
		this.panelMain.setSizeUndefined();
		this.gridLayout.addComponent(this.panelMain, 0, 0);
		this.gridLayout.setComponentAlignment(this.panelMain, Alignment.MIDDLE_CENTER);
		this.panelOauth.setSizeUndefined();
		this.gridLayout.addComponent(this.panelOauth, 0, 1);
		this.gridLayout.setComponentAlignment(this.panelOauth, Alignment.MIDDLE_CENTER);
		this.panelLocal.setSizeUndefined();
		this.gridLayout.addComponent(this.panelLocal, 1, 1);
		this.gridLayout.setComponentAlignment(this.panelLocal, Alignment.MIDDLE_CENTER);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setRowExpandRatio(0, 10.0F);
		this.gridLayout.setRowExpandRatio(1, 10.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();

		this.cmdLoginLocal.addClickListener(event -> this.cmdLoginLocal_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton cmdLogin, cmdLoginLocal;
	private XdevPasswordField txtPassword;
	private XdevPanel panelMain, panelOauth, panelLocal;
	private XdevGridLayout gridLayout, gridLayout4, gridLayout2, gridLayout3;
	private XdevTextField txtUsername;
	// </generated-code>

}
