package ch.xwr.seicentobilling.ui.desktop;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.Set;

import com.vaadin.server.FileDownloader;
import com.vaadin.server.FontAwesome;
import com.vaadin.server.Resource;
import com.vaadin.server.StreamResource;
import com.vaadin.ui.Button;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Table;
import com.vaadin.ui.Table.ColumnGenerator;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.table.XdevTable;

import ch.xwr.seicentobilling.business.RowObjectManager;
import ch.xwr.seicentobilling.entities.Expense;
import ch.xwr.seicentobilling.entities.RowImage;
import ch.xwr.seicentobilling.entities.RowObject;

public class FunctionExpenseAttachmentDownload extends XdevView {
	private Table customizedTable = null;
	private Object itemId = null;
	private Object columnId = null;
	private RowImage rowFile = null;

	public static class Generator implements ColumnGenerator {
		@Override
		public Object generateCell(final Table table, final Object itemId, final Object columnId) {

			return new FunctionExpenseAttachmentDownload(table, itemId, columnId);
		}
	}

	private FunctionExpenseAttachmentDownload(final Table customizedTable, final Object itemId, final Object columnId) {
		super();

		this.customizedTable = customizedTable;
		this.itemId = itemId;
		this.columnId = columnId;
		this.rowFile = getBean();

		this.initUI();

		if (this.rowFile != null) {
			this.cmdDownload.setDescription("Download " + this.rowFile.getRimName());

			//Downloader init
			final Resource res = getInputStream();
			final FileDownloader fd = new FileDownloader(res);
			fd.extend(this.cmdDownload);
		} else {
			this.cmdDownload.setEnabled(false);
		}
	}

	public Table getTable() {
		return this.customizedTable;
	}

	public Object getItemId() {
		return this.itemId;
	}

	public Object getColumnId() {
		return this.columnId;
	}

	@SuppressWarnings("unchecked")
	public RowImage getBean() {
		RowImage img = null;
		final Expense exp = ((XdevTable<Expense>) getTable()).getBeanContainerDataSource().getItem(getItemId()).getBean();

		final RowObjectManager man = new RowObjectManager();
		final RowObject obj = man.getRowObject(exp.getClass().getSimpleName(), exp.getExpId());

		if (obj != null) {
			final Set<RowImage> ls = obj.getRowImages();
			if (ls !=null && ls.size()>0) {
				img = ls.iterator().next();
			}
		}

		return img;
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdDownload}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdDownload_buttonClick(final Button.ClickEvent event) {
		selectItem();

		//File temp = writeToTempFile(getBean());
		startDownload();
	}

	private void startDownload() {
		Notification.show("Download gestartet für: " + this.rowFile.getRimName(), Notification.Type.TRAY_NOTIFICATION);
	}

	private Resource getInputStream() {
        final StreamResource.StreamSource source = new StreamResource.StreamSource() {
            @Override
            public InputStream getStream() {
                final ByteArrayInputStream inStream = new ByteArrayInputStream(FunctionExpenseAttachmentDownload.this.rowFile.getRimImage());
                return inStream;
            }
        };

		final Resource res = new StreamResource(source, this.rowFile.getRimName());

		return res;
	}

	private void selectItem() {
		getTable().select(getItemId());
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.cmdDownload = new XdevButton();

		this.cmdDownload.setIcon(FontAwesome.DOWNLOAD);
		this.cmdDownload.setDescription("Download attachment");
		this.cmdDownload.setStyleName("tiny");

		this.cmdDownload.setSizeUndefined();
		this.setContent(this.cmdDownload);
		this.setSizeFull();

		this.cmdDownload.addClickListener(event -> this.cmdDownload_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton cmdDownload;
	// </generated-code>

}
