package ch.xwr.seicentobilling.ui.desktop;

import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.UI;
import com.vaadin.ui.Upload;
import com.vaadin.ui.Upload.SucceededEvent;
import com.vaadin.ui.Window;
import com.xdev.dal.DAOs;
import com.xdev.res.ApplicationResource;
import com.xdev.res.StringResourceUtils;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevFieldGroup;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevPanel;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevUpload;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.combobox.XdevComboBox;

import ch.xwr.seicentobilling.business.LovState;
import ch.xwr.seicentobilling.business.UploadReceiver;
import ch.xwr.seicentobilling.dal.RowImageDAO;
import ch.xwr.seicentobilling.dal.RowObjectDAO;
import ch.xwr.seicentobilling.entities.RowImage;
import ch.xwr.seicentobilling.entities.RowImage_;
import ch.xwr.seicentobilling.entities.RowObject;
import ch.xwr.seicentobilling.entities.RowObject_;

public class RowFilePopup extends XdevView {

	/**
	 *
	 */
	public RowFilePopup() {
		super();
		this.initUI();

		//State
		this.comboBoxState.addItems((Object[])LovState.State.values());

		//get Parameter
		final Long beanId = (Long) UI.getCurrent().getSession().getAttribute("beanId");
		final Long objId = (Long) UI.getCurrent().getSession().getAttribute("objId");
		RowImage bean = null;
		RowObject obj = null;

		if (beanId == null) {
			//new
			final RowObjectDAO objDao = new RowObjectDAO();
			obj = objDao.find(objId);

			bean = new RowImage();
			bean.setRimState(LovState.State.active);
			bean.setRowObject(obj);

		} else {
			final RowImageDAO dao = new RowImageDAO();
			bean = dao.find(beanId.longValue());
		}

		setBeanGui(bean);
		setupUploader(bean);
	}

	public static Window getPopupWindow() {
		final Window win = new Window();

		win.setWidth("670");
		win.setHeight("550");
		win.center();
		win.setModal(true);
		win.setContent(new RowFilePopup());

		return win;
	}

	private void setupUploader(final RowImage bean) {
		//uploader
		final UploadReceiver rec = new UploadReceiver(bean);
        //upload.setImmediate(true);
        //upload.setButtonCaption("Upload File");
		this.upload.setReceiver(rec);

        this.upload.addSucceededListener(new Upload.SucceededListener() {
            @Override
			public void uploadSucceeded(final SucceededEvent event) {
                // This method gets called when the upload finished successfully
        	    System.out.println("________________ UPLOAD SUCCEEDED y");

        	    rec.uploadSucceeded(event);
        	    setBeanGui(rec.getBean());
            }
        });
	}

	private void setBeanGui(final RowImage bean) {
		//set Bean + Fields
		this.fieldGroup.setItemDataSource(bean);

		this.comboBoxObject.setEnabled(false);
		this.textFieldSize.setEnabled(false);
		this.textFieldName.setEnabled(false);
		this.textFieldMime.setEnabled(false);
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdReset}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdReset_buttonClick(final Button.ClickEvent event) {
		((Window) this.getParent()).close();

	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdSave}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_buttonClick(final Button.ClickEvent event) {
		UI.getCurrent().getSession().setAttribute(String.class, "cmdSave");
		this.fieldGroup.save();
		((Window) this.getParent()).close();

	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.panel = new XdevPanel();
		this.form = new XdevGridLayout();
		this.labelObject = new XdevLabel();
		this.comboBoxObject = new XdevComboBox<>();
		this.labelNbr = new XdevLabel();
		this.textField = new XdevTextField();
		this.labelFile = new XdevLabel();
		this.textFieldName = new XdevTextField();
		this.upload = new XdevUpload();
		this.lblMimeType = new XdevLabel();
		this.textFieldMime = new XdevTextField();
		this.textField4 = new XdevTextField();
		this.labelSize = new XdevLabel();
		this.textFieldSize = new XdevTextField();
		this.comboBoxState = new XdevComboBox<>();
		this.labelType = new XdevLabel();
		this.labelState = new XdevLabel();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.cmdSave = new XdevButton();
		this.cmdReset = new XdevButton();
		this.fieldGroup = new XdevFieldGroup<>(RowImage.class);

		this.labelObject.setValue(StringResourceUtils.optLocalizeString("{$labelObject.value}", this));
		this.comboBoxObject.setItemCaptionFromAnnotation(false);
		this.comboBoxObject.setContainerDataSource(RowObject.class, DAOs.get(RowObjectDAO.class).findAll());
		this.comboBoxObject.setItemCaptionPropertyId(RowObject_.entity.getName());
		this.labelNbr.setValue(StringResourceUtils.optLocalizeString("{$labelNbr.value}", this));
		this.textField.setColumns(5);
		this.textField.setTabIndex(2);
		this.labelFile.setValue(StringResourceUtils.optLocalizeString("{$labelFile.value}", this));
		this.textFieldName.setTabIndex(3);
		this.upload.setTabIndex(14);
		this.upload.setImmediate(true);
		this.lblMimeType.setValue(StringResourceUtils.optLocalizeString("{$lblMimeType.value}", this));
		this.textFieldMime.setTabIndex(15);
		this.textField4.setColumns(5);
		this.textField4.setTabIndex(16);
		this.labelSize.setValue(StringResourceUtils.optLocalizeString("{$labelSize.value}", this));
		this.textFieldSize.setTabIndex(18);
		this.comboBoxState.setTabIndex(19);
		this.labelType.setValue(StringResourceUtils.optLocalizeString("{$labelType.value}", this));
		this.labelState.setValue(StringResourceUtils.optLocalizeString("{$labelState.value}", this));
		this.horizontalLayout.setMargin(new MarginInfo(false));
		this.cmdSave.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/save1.png"));
		this.cmdSave.setCaption(StringResourceUtils.optLocalizeString("{$cmdSave.caption}", this));
		this.cmdSave.setTabIndex(20);
		this.cmdReset.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/cancel1.png"));
		this.cmdReset.setCaption(StringResourceUtils.optLocalizeString("{$cmdReset.caption}", this));
		this.cmdReset.setTabIndex(21);
		this.fieldGroup.bind(this.comboBoxObject, RowImage_.rowObject.getName());
		this.fieldGroup.bind(this.textField, RowImage_.rimNumber.getName());
		this.fieldGroup.bind(this.textFieldName, RowImage_.rimName.getName());
		this.fieldGroup.bind(this.textFieldMime, RowImage_.rimMimetype.getName());
		this.fieldGroup.bind(this.textField4, RowImage_.rimType.getName());
		this.fieldGroup.bind(this.textFieldSize, RowImage_.rimSize.getName());
		this.fieldGroup.bind(this.comboBoxState, RowImage_.rimState.getName());

		this.cmdSave.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdSave);
		this.horizontalLayout.setComponentAlignment(this.cmdSave, Alignment.MIDDLE_LEFT);
		this.cmdReset.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdReset);
		this.horizontalLayout.setComponentAlignment(this.cmdReset, Alignment.MIDDLE_LEFT);
		this.form.setColumns(3);
		this.form.setRows(9);
		this.labelObject.setSizeUndefined();
		this.form.addComponent(this.labelObject, 0, 0);
		this.comboBoxObject.setWidth(100, Unit.PERCENTAGE);
		this.comboBoxObject.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.comboBoxObject, 1, 0);
		this.labelNbr.setSizeUndefined();
		this.form.addComponent(this.labelNbr, 0, 1);
		this.textField.setSizeUndefined();
		this.form.addComponent(this.textField, 1, 1);
		this.labelFile.setSizeUndefined();
		this.form.addComponent(this.labelFile, 0, 2);
		this.textFieldName.setWidth(100, Unit.PERCENTAGE);
		this.textFieldName.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.textFieldName, 1, 2);
		this.upload.setSizeUndefined();
		this.form.addComponent(this.upload, 2, 2);
		this.lblMimeType.setSizeUndefined();
		this.form.addComponent(this.lblMimeType, 0, 3);
		this.textFieldMime.setWidth(100, Unit.PERCENTAGE);
		this.textFieldMime.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.textFieldMime, 1, 3);
		this.textField4.setSizeUndefined();
		this.form.addComponent(this.textField4, 1, 4);
		this.labelSize.setSizeUndefined();
		this.form.addComponent(this.labelSize, 0, 5);
		this.textFieldSize.setWidth(100, Unit.PERCENTAGE);
		this.textFieldSize.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.textFieldSize, 1, 5);
		this.comboBoxState.setSizeUndefined();
		this.form.addComponent(this.comboBoxState, 1, 6);
		this.labelType.setSizeUndefined();
		this.form.addComponent(this.labelType, 0, 4);
		this.labelState.setSizeUndefined();
		this.form.addComponent(this.labelState, 0, 6);
		this.horizontalLayout.setSizeUndefined();
		this.form.addComponent(this.horizontalLayout, 1, 7);
		this.form.setComponentAlignment(this.horizontalLayout, Alignment.TOP_RIGHT);
		this.form.setColumnExpandRatio(2, 10.0F);
		final CustomComponent form_vSpacer = new CustomComponent();
		form_vSpacer.setSizeFull();
		this.form.addComponent(form_vSpacer, 0, 8, 2, 8);
		this.form.setRowExpandRatio(8, 1.0F);
		this.form.setSizeFull();
		this.panel.setContent(this.form);
		this.panel.setSizeFull();
		this.setContent(this.panel);
		this.setSizeFull();

		this.cmdSave.addClickListener(event -> this.cmdSave_buttonClick(event));
		this.cmdReset.addClickListener(event -> this.cmdReset_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel labelObject, labelNbr, labelFile, lblMimeType, labelSize, labelType, labelState;
	private XdevButton cmdSave, cmdReset;
	private XdevUpload upload;
	private XdevHorizontalLayout horizontalLayout;
	private XdevComboBox<RowObject> comboBoxObject;
	private XdevFieldGroup<RowImage> fieldGroup;
	private XdevComboBox<?> comboBoxState;
	private XdevPanel panel;
	private XdevGridLayout form;
	private XdevTextField textField, textFieldName, textFieldMime, textField4, textFieldSize;
	// </generated-code>


}
