package ch.xwr.seicentobilling.ui.desktop;

import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.xdev.res.ApplicationResource;
import com.xdev.res.StringResourceUtils;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevFieldGroup;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevPanel;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.combobox.XdevComboBox;

import ch.xwr.seicentobilling.business.LovState;
import ch.xwr.seicentobilling.dal.RowObjectDAO;
import ch.xwr.seicentobilling.dal.RowParameterDAO;
import ch.xwr.seicentobilling.entities.RowObject;
import ch.xwr.seicentobilling.entities.RowParameter;
import ch.xwr.seicentobilling.entities.RowParameter_;

public class RowParamPopup extends XdevView {

	/**
	 *
	 */
	public RowParamPopup() {
		super();
		this.initUI();

		//State
		this.comboBoxState.addItems((Object[])LovState.State.values());
		this.cbxValueType.addItems((Object[])LovState.ValueType.values());


		//get Parameter
		final Long beanId = (Long) UI.getCurrent().getSession().getAttribute("beanId");
		final Long objId = (Long) UI.getCurrent().getSession().getAttribute("objId");
		RowParameter bean = null;
		RowObject obj = null;

		if (beanId == null) {
			//new
			final RowObjectDAO objDao = new RowObjectDAO();
			obj = objDao.find(objId);

			bean = new RowParameter();
			bean.setPrmState(LovState.State.active);
			//bean.setLanguage(lng);
			bean.setRowObject(obj);

		} else {
			final RowParameterDAO dao = new RowParameterDAO();
			bean = dao.find(beanId.longValue());
		}

		this.fieldGroup.setItemDataSource(bean);
		//this.cmbRowObject.setEnabled(false);

	}


	public static Window getPopupWindow() {
		final Window win = new Window();
		win.setWidth("670");
		win.setHeight("420");
		win.center();
		win.setModal(true);
		win.setContent(new RowParamPopup());

		return win;
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdReset}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdReset_buttonClick(final Button.ClickEvent event) {
		this.fieldGroup.discard();
		((Window) this.getParent()).close();
	}


	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdSave}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_buttonClick(final Button.ClickEvent event) {
		UI.getCurrent().getSession().setAttribute(String.class, "cmdSave");
		this.fieldGroup.save();
		((Window) this.getParent()).close();
	}


	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.panel = new XdevPanel();
		this.form = new XdevGridLayout();
		this.cbxValueType = new XdevComboBox<>();
		this.comboBoxState = new XdevComboBox<>();
		this.lblPrmGroup = new XdevLabel();
		this.txtPrmGroup = new XdevTextField();
		this.lblPrmSubGroup = new XdevLabel();
		this.txtPrmSubGroup = new XdevTextField();
		this.lblPrmKey = new XdevLabel();
		this.txtPrmKey = new XdevTextField();
		this.lblPrmValue = new XdevLabel();
		this.txtPrmValue = new XdevTextField();
		this.lblPrmValueType = new XdevLabel();
		this.lblPrmState = new XdevLabel();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.cmdSave = new XdevButton();
		this.cmdReset = new XdevButton();
		this.fieldGroup = new XdevFieldGroup<>(RowParameter.class);

		this.cbxValueType.setTabIndex(24);
		this.comboBoxState.setTabIndex(25);
		this.lblPrmGroup.setValue(StringResourceUtils.optLocalizeString("{$lblPrmGroup.value}", this));
		this.txtPrmGroup.setTabIndex(20);
		this.lblPrmSubGroup.setValue(StringResourceUtils.optLocalizeString("{$lblPrmSubGroup.value}", this));
		this.txtPrmSubGroup.setTabIndex(21);
		this.lblPrmKey.setValue(StringResourceUtils.optLocalizeString("{$lblPrmKey.value}", this));
		this.txtPrmKey.setTabIndex(22);
		this.lblPrmValue.setValue(StringResourceUtils.optLocalizeString("{$lblPrmValue.value}", this));
		this.txtPrmValue.setTabIndex(23);
		this.lblPrmValueType.setValue(StringResourceUtils.optLocalizeString("{$lblPrmValueType.value}", this));
		this.lblPrmState.setValue(StringResourceUtils.optLocalizeString("{$lblPrmState.value}", this));
		this.horizontalLayout.setMargin(new MarginInfo(false));
		this.cmdSave.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/save1.png"));
		this.cmdSave.setCaption(StringResourceUtils.optLocalizeString("{$cmdSave.caption}", this));
		this.cmdSave.setTabIndex(12);
		this.cmdReset.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/cancel1.png"));
		this.cmdReset.setCaption(StringResourceUtils.optLocalizeString("{$cmdReset.caption}", this));
		this.cmdReset.setTabIndex(11);
		this.fieldGroup.bind(this.txtPrmGroup, RowParameter_.prmGroup.getName());
		this.fieldGroup.bind(this.txtPrmSubGroup, RowParameter_.prmSubGroup.getName());
		this.fieldGroup.bind(this.txtPrmKey, RowParameter_.prmKey.getName());
		this.fieldGroup.bind(this.txtPrmValue, RowParameter_.prmValue.getName());
		this.fieldGroup.bind(this.cbxValueType, RowParameter_.prmValueType.getName());
		this.fieldGroup.bind(this.comboBoxState, RowParameter_.prmState.getName());

		this.cmdSave.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdSave);
		this.horizontalLayout.setComponentAlignment(this.cmdSave, Alignment.MIDDLE_CENTER);
		this.cmdReset.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdReset);
		this.horizontalLayout.setComponentAlignment(this.cmdReset, Alignment.MIDDLE_RIGHT);
		this.form.setColumns(2);
		this.form.setRows(8);
		this.cbxValueType.setSizeUndefined();
		this.form.addComponent(this.cbxValueType, 1, 4);
		this.comboBoxState.setSizeUndefined();
		this.form.addComponent(this.comboBoxState, 1, 5);
		this.lblPrmGroup.setSizeUndefined();
		this.form.addComponent(this.lblPrmGroup, 0, 0);
		this.txtPrmGroup.setWidth(100, Unit.PERCENTAGE);
		this.txtPrmGroup.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.txtPrmGroup, 1, 0);
		this.lblPrmSubGroup.setSizeUndefined();
		this.form.addComponent(this.lblPrmSubGroup, 0, 1);
		this.txtPrmSubGroup.setWidth(100, Unit.PERCENTAGE);
		this.txtPrmSubGroup.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.txtPrmSubGroup, 1, 1);
		this.lblPrmKey.setSizeUndefined();
		this.form.addComponent(this.lblPrmKey, 0, 2);
		this.txtPrmKey.setWidth(100, Unit.PERCENTAGE);
		this.txtPrmKey.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.txtPrmKey, 1, 2);
		this.lblPrmValue.setSizeUndefined();
		this.form.addComponent(this.lblPrmValue, 0, 3);
		this.txtPrmValue.setWidth(100, Unit.PERCENTAGE);
		this.txtPrmValue.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.txtPrmValue, 1, 3);
		this.lblPrmValueType.setSizeUndefined();
		this.form.addComponent(this.lblPrmValueType, 0, 4);
		this.lblPrmState.setSizeUndefined();
		this.form.addComponent(this.lblPrmState, 0, 5);
		this.horizontalLayout.setSizeUndefined();
		this.form.addComponent(this.horizontalLayout, 0, 6, 1, 6);
		this.form.setComponentAlignment(this.horizontalLayout, Alignment.MIDDLE_CENTER);
		this.form.setColumnExpandRatio(1, 100.0F);
		final CustomComponent form_vSpacer = new CustomComponent();
		form_vSpacer.setSizeFull();
		this.form.addComponent(form_vSpacer, 0, 7, 1, 7);
		this.form.setRowExpandRatio(7, 1.0F);
		this.form.setSizeFull();
		this.panel.setContent(this.form);
		this.panel.setSizeFull();
		this.setContent(this.panel);
		this.setSizeFull();

		this.cmdSave.addClickListener(event -> this.cmdSave_buttonClick(event));
		this.cmdReset.addClickListener(event -> this.cmdReset_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel lblPrmGroup, lblPrmSubGroup, lblPrmKey, lblPrmValue, lblPrmValueType, lblPrmState;
	private XdevButton cmdSave, cmdReset;
	private XdevHorizontalLayout horizontalLayout;
	private XdevFieldGroup<RowParameter> fieldGroup;
	private XdevComboBox<?> cbxValueType, comboBoxState;
	private XdevPanel panel;
	private XdevGridLayout form;
	private XdevTextField txtPrmGroup, txtPrmSubGroup, txtPrmKey, txtPrmValue;
	// </generated-code>

}
