package ch.xwr.seicentobilling.ui.desktop;

import java.util.List;

import com.vaadin.server.FontAwesome;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.xdev.dal.DAOs;
import com.xdev.res.StringResourceUtils;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevFieldGroup;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevPanel;
import com.xdev.ui.XdevTextArea;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.combobox.XdevComboBox;

import ch.xwr.seicentobilling.business.LovState;
import ch.xwr.seicentobilling.dal.LanguageDAO;
import ch.xwr.seicentobilling.dal.RowObjectDAO;
import ch.xwr.seicentobilling.dal.RowTextDAO;
import ch.xwr.seicentobilling.entities.Language;
import ch.xwr.seicentobilling.entities.Language_;
import ch.xwr.seicentobilling.entities.RowObject;
import ch.xwr.seicentobilling.entities.RowObject_;
import ch.xwr.seicentobilling.entities.RowText;
import ch.xwr.seicentobilling.entities.RowText_;

public class RowTextPopup extends XdevView {

	/**
	 *
	 */
	public RowTextPopup() {
		super();
		this.initUI();

		//State
		this.comboBoxState.addItems((Object[])LovState.State.values());


		//get Parameter
		final Long beanId = (Long) UI.getCurrent().getSession().getAttribute("beanId");
		final Long objId = (Long) UI.getCurrent().getSession().getAttribute("objId");
		RowText bean = null;
		RowObject obj = null;

		if (beanId == null) {
			//new
			final RowObjectDAO objDao = new RowObjectDAO();
			obj = objDao.find(objId);

			final List<Language> llst = new LanguageDAO().findAll();
			Language lng = null;
			if (llst.size()>0) {
				lng = llst.get(0);
			}

			bean = new RowText();
			bean.setTxtState(LovState.State.active);
			bean.setTxtNumber(0);
			bean.setTxtFreetext("");
			bean.setLanguage(lng);
			bean.setRowObject(obj);

		} else {
			final RowTextDAO dao = new RowTextDAO();
			bean = dao.find(beanId.longValue());
		}

		this.fieldGroup.setItemDataSource(bean);

		this.comboBoxObject.setEnabled(false);
	}

	public static Window getPopupWindow() {
		final Window win = new Window();
		win.setWidth("670");
		win.setHeight("520");
		win.center();
		win.setModal(true);
		win.setContent(new RowTextPopup());

		return win;
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdCancel}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdCancel_buttonClick(final Button.ClickEvent event) {
		((Window) this.getParent()).close();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdSave}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_buttonClick(final Button.ClickEvent event) {
		UI.getCurrent().getSession().setAttribute(String.class, "cmdSave");
		this.fieldGroup.save();
		((Window) this.getParent()).close();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.panel = new XdevPanel();
		this.form = new XdevGridLayout();
		this.textArea = new XdevTextArea();
		this.comboBoxState = new XdevComboBox<>();
		this.label = new XdevLabel();
		this.comboBoxObject = new XdevComboBox<>();
		this.label2 = new XdevLabel();
		this.textField = new XdevTextField();
		this.label3 = new XdevLabel();
		this.label4 = new XdevLabel();
		this.comboBox2 = new XdevComboBox<>();
		this.label5 = new XdevLabel();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.cmdSave = new XdevButton();
		this.cmdCancel = new XdevButton();
		this.fieldGroup = new XdevFieldGroup<>(RowText.class);

		this.textArea.setRows(8);
		this.label.setValue(StringResourceUtils.optLocalizeString("{$label.value}", this));
		this.comboBoxObject.setItemCaptionFromAnnotation(false);
		this.comboBoxObject.setEnabled(false);
		this.comboBoxObject.setContainerDataSource(RowObject.class, DAOs.get(RowObjectDAO.class).findAll());
		this.comboBoxObject.setItemCaptionPropertyId(RowObject_.entity.getName());
		this.label2.setValue(StringResourceUtils.optLocalizeString("{$label2.value}", this));
		this.label3.setValue(StringResourceUtils.optLocalizeString("{$label3.value}", this));
		this.label4.setValue(StringResourceUtils.optLocalizeString("{$label4.value}", this));
		this.comboBox2.setItemCaptionFromAnnotation(false);
		this.comboBox2.setContainerDataSource(Language.class);
		this.comboBox2.setItemCaptionPropertyId(Language_.lngName.getName());
		this.label5.setValue(StringResourceUtils.optLocalizeString("{$label5.value}", this));
		this.horizontalLayout.setMargin(new MarginInfo(false));
		this.cmdSave.setIcon(FontAwesome.SAVE);
		this.cmdSave.setCaption(StringResourceUtils.optLocalizeString("{$cmdSave.caption}", this));
		this.cmdCancel.setIcon(FontAwesome.CLOSE);
		this.cmdCancel.setCaption(StringResourceUtils.optLocalizeString("{$cmdCancel.caption}", this));
		this.fieldGroup.bind(this.comboBoxObject, RowText_.rowObject.getName());
		this.fieldGroup.bind(this.textField, RowText_.txtNumber.getName());
		this.fieldGroup.bind(this.textArea, RowText_.txtFreetext.getName());
		this.fieldGroup.bind(this.comboBox2, RowText_.language.getName());
		this.fieldGroup.bind(this.comboBoxState, RowText_.txtState.getName());

		this.cmdSave.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdSave);
		this.horizontalLayout.setComponentAlignment(this.cmdSave, Alignment.MIDDLE_LEFT);
		this.cmdCancel.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdCancel);
		this.horizontalLayout.setComponentAlignment(this.cmdCancel, Alignment.MIDDLE_LEFT);
		final CustomComponent horizontalLayout_spacer = new CustomComponent();
		horizontalLayout_spacer.setSizeFull();
		this.horizontalLayout.addComponent(horizontalLayout_spacer);
		this.horizontalLayout.setExpandRatio(horizontalLayout_spacer, 1.0F);
		this.form.setColumns(2);
		this.form.setRows(7);
		this.textArea.setWidth(100, Unit.PERCENTAGE);
		this.textArea.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.textArea, 1, 2);
		this.comboBoxState.setSizeUndefined();
		this.form.addComponent(this.comboBoxState, 1, 4);
		this.label.setSizeUndefined();
		this.form.addComponent(this.label, 0, 0);
		this.comboBoxObject.setWidth(100, Unit.PERCENTAGE);
		this.comboBoxObject.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.comboBoxObject, 1, 0);
		this.label2.setSizeUndefined();
		this.form.addComponent(this.label2, 0, 1);
		this.textField.setSizeUndefined();
		this.form.addComponent(this.textField, 1, 1);
		this.label3.setSizeUndefined();
		this.form.addComponent(this.label3, 0, 2);
		this.label4.setSizeUndefined();
		this.form.addComponent(this.label4, 0, 3);
		this.comboBox2.setSizeUndefined();
		this.form.addComponent(this.comboBox2, 1, 3);
		this.label5.setSizeUndefined();
		this.form.addComponent(this.label5, 0, 4);
		this.horizontalLayout.setSizeFull();
		this.form.addComponent(this.horizontalLayout, 1, 5);
		this.form.setComponentAlignment(this.horizontalLayout, Alignment.TOP_RIGHT);
		this.form.setColumnExpandRatio(1, 10.0F);
		final CustomComponent form_vSpacer = new CustomComponent();
		form_vSpacer.setSizeFull();
		this.form.addComponent(form_vSpacer, 0, 6, 1, 6);
		this.form.setRowExpandRatio(6, 1.0F);
		this.form.setWidth(100, Unit.PERCENTAGE);
		this.form.setHeight(-1, Unit.PIXELS);
		this.panel.setContent(this.form);
		this.panel.setSizeFull();
		this.setContent(this.panel);
		this.setSizeFull();

		this.cmdSave.addClickListener(event -> this.cmdSave_buttonClick(event));
		this.cmdCancel.addClickListener(event -> this.cmdCancel_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel label, label2, label3, label4, label5;
	private XdevButton cmdSave, cmdCancel;
	private XdevHorizontalLayout horizontalLayout;
	private XdevComboBox<RowObject> comboBoxObject;
	private XdevTextArea textArea;
	private XdevPanel panel;
	private XdevGridLayout form;
	private XdevTextField textField;
	private XdevComboBox<CustomComponent> comboBoxState;
	private XdevFieldGroup<RowText> fieldGroup;
	private XdevComboBox<Language> comboBox2;
	// </generated-code>


}
