
package ch.xwr.seicentobilling.ui.phone;

import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.server.ClientConnector;
import com.vaadin.server.VaadinSession;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.UI;
import com.xdev.res.ApplicationResource;
import com.xdev.security.authorization.Subject;
import com.xdev.server.aa.openid.auth.AzureUser;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevView;
import com.xdev.ui.navigation.Navigation;

import ch.xwr.seicentobilling.business.Seicento;
import ch.xwr.seicentobilling.business.auth.SeicentoUser;


public class MainView extends XdevView {
	private SeicentoUser currentUser;

	/**
	 *
	 */
	public MainView() {
		super();
		this.initUI();
	}

	@Override
	public void enter(final ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);

	}

	/**
	 * Event handler delegate method for the {@link XdevGridLayout}
	 * {@link #gridLayout}.
	 *
	 * @see ClientConnector.AttachListener#attach(ClientConnector.AttachEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void gridLayout_attach(final ClientConnector.AttachEvent event) {
		final Subject sub = VaadinSession.getCurrent().getAttribute(Subject.class);
		this.currentUser = new SeicentoUser();

		if (sub != null && sub instanceof AzureUser)
		{
			this.currentUser.setAzureUser((AzureUser) sub);
		} else if (sub != null && sub instanceof SeicentoUser){
			this.currentUser = (SeicentoUser) sub;
		}
		if (this.currentUser.getAssignedAccount() == null) {
			this.currentUser.setAssignedAccount(Seicento.getLoggedInCostAccount(this.currentUser.name()));
		}
		VaadinSession.getCurrent().setAttribute(Subject.class, this.currentUser);

		final UI ux = this.getUI();
		if (ux instanceof PhoneUI) {
			final PhoneUI main = (PhoneUI) this.getUI(); //.getParent().getUI();
			main.loggedIn(true, this.currentUser);
		} else {
			System.out.println("logged in Preview / DevEnv. PhoneUI not available!");
			Seicento.removeGelfAppender();
		}
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdExpense}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdExpense_buttonClick(final Button.ClickEvent event) {
		Navigation.to("periodeView").parameter("string", "Expense").navigate();

	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdProjectLine}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdProjectLine_buttonClick(final Button.ClickEvent event) {
		Navigation.to("periodeView").parameter("string", "ProjectLine").navigate();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdAddress}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdAddress_buttonClick(final Button.ClickEvent event) {
		Navigation.to("addressSearchView").navigate();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.cmdExpense = new XdevButton();
		this.cmdProjectLine = new XdevButton();
		this.cmdAddress = new XdevButton();

		this.gridLayout.setResponsive(true);
		this.cmdExpense
				.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/expense48.png"));
		this.cmdExpense.setCaption("Spesen");
		this.cmdProjectLine.setIcon(
				new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/TimeMaterial48.png"));
		this.cmdProjectLine.setCaption("Rapporte");
		this.cmdAddress
				.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/Customers-48.png"));
		this.cmdAddress.setCaption("Adressen");

		this.gridLayout.setColumns(2);
		this.gridLayout.setRows(2);
		this.cmdExpense.setWidth(150, Unit.PIXELS);
		this.cmdExpense.setHeight(150, Unit.PIXELS);
		this.gridLayout.addComponent(this.cmdExpense, 0, 0);
		this.gridLayout.setComponentAlignment(this.cmdExpense, Alignment.MIDDLE_LEFT);
		this.cmdProjectLine.setWidth(150, Unit.PIXELS);
		this.cmdProjectLine.setHeight(150, Unit.PIXELS);
		this.gridLayout.addComponent(this.cmdProjectLine, 1, 0);
		this.gridLayout.setComponentAlignment(this.cmdProjectLine, Alignment.MIDDLE_LEFT);
		this.cmdAddress.setWidth(150, Unit.PIXELS);
		this.cmdAddress.setHeight(150, Unit.PIXELS);
		this.gridLayout.addComponent(this.cmdAddress, 0, 1);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setColumnExpandRatio(1, 10.0F);
		this.gridLayout.setRowExpandRatio(0, 20.0F);
		this.gridLayout.setRowExpandRatio(1, 20.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();

		this.gridLayout.addAttachListener(event -> this.gridLayout_attach(event));
		this.cmdExpense.addClickListener(event -> this.cmdExpense_buttonClick(event));
		this.cmdProjectLine.addClickListener(event -> this.cmdProjectLine_buttonClick(event));
		this.cmdAddress.addClickListener(event -> this.cmdAddress_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton cmdExpense, cmdProjectLine, cmdAddress;
	private XdevGridLayout gridLayout;
	// </generated-code>

}
