
package ch.xwr.seicentobilling.ui.phone;

import java.util.Locale;
import java.util.TimeZone;

import com.vaadin.annotations.Push;
import com.vaadin.annotations.Theme;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.shared.communication.PushMode;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.shared.ui.ui.Transport;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.xdev.res.ApplicationResource;
import com.xdev.security.authentication.ui.XdevAuthenticationNavigator;
import com.xdev.server.aa.openid.auth.AzureUser;
import com.xdev.server.aa.openid.helper.DiscoveryHelper;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevImage;
import com.xdev.ui.XdevUI;
import com.xdev.ui.XdevVerticalLayout;
import com.xdev.ui.navigation.Navigation;

import ch.xwr.seicentobilling.business.helper.AzureHelper;
import ch.xwr.seicentobilling.dal.CompanyDAO;
import ch.xwr.seicentobilling.entities.Company;

@Push(value = PushMode.MANUAL, transport = Transport.LONG_POLLING)
@Theme("SeicentoBilling")
public class PhoneUI extends XdevUI {
	/** Logger initialized */
	private static final org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(PhoneUI.class);
	private AzureUser currentUser;

	public PhoneUI() {
		super();

		//mj DiscoveryHelper for setup AAD
		try {
			DiscoveryHelper.performDiscovery(VaadinServlet.getCurrent().getServletContext());
		} catch (final Throwable e) {
			e.printStackTrace();
		}
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public void init(final VaadinRequest request) {
		setLocale();
		this.initUI();
		checkLocalDevEnv();
		setCallBackUri();
		loadMyData();
	}

	private void loadMyData() {
		LOG.info("Load company Data for Phone...");

		final CompanyDAO dao = new CompanyDAO();
		final Company cmp = dao.getActiveConfig();

		LOG.debug(cmp.getCmpName());

//		this.lblEnvironment.setValue(dao.getDbNameNativeSQL());
//		this.lblCompany.setValue(cmp.getCmpName());
	}


	//will be consumed in AuthView
	private void setCallBackUri() {
		final AzureHelper hlp = new AzureHelper();
		hlp.setCallBackUri(this.getPage().getLocation());
	}


	//only for local testing with preview
	private void checkLocalDevEnv() {
		final String path = this.getPage().getLocation().getPath();

		if (path == null || path.length() < 3) {
			//Eclipse Preview (does not have Path in Jetty)
			//enableMenu(true);
			LOG.debug("Dev System");

			//this.currentUser = new AzureUser(null);

//			this.menuBarRight.setVisible(false);
//			this.menuBarRight.setEnabled(false);
		}
	}


	public void loggedIn(final boolean lgin, final AzureUser user) {
		this.currentUser = user;
		setLocale();

//		if (lgin) {
//			//this.menuItemUser.setCaption(this.currentUser.name());
//		} else {
//			//this.menuItemUser.setCaption("");
//		}

		//enableMenu(lgin);

		LOG.debug("User: " + this.currentUser.name());
	}

	//auf Azure App Service ist diese auf en-US
	private void setLocale() {
		Locale.setDefault(new Locale("de", "CH"));
		TimeZone.setDefault(TimeZone.getTimeZone("Europe/Zurich"));
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #button}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void button_buttonClick(final Button.ClickEvent event) {
		goHome();
	}


	private void goHome() {
		Navigation.to("home").navigate();

	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.verticalLayout = new XdevVerticalLayout();
		this.horizontalLayoutTitle = new XdevHorizontalLayout();
		this.image = new XdevImage();
		this.button = new XdevButton();
		this.container = new XdevVerticalLayout();
		this.navigator = new XdevAuthenticationNavigator(this, this.container);

		this.verticalLayout.setSpacing(false);
		this.verticalLayout.setMargin(new MarginInfo(false));
		this.horizontalLayoutTitle.setMargin(new MarginInfo(false));
		this.image.setSource(
				new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/Seicento_Billing.png"));
		this.button.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/home32.png"));
		this.container.setMargin(new MarginInfo(false));
		this.navigator.setRedirectViewName("home");
		this.navigator.addView("", AuthView.class);
		this.navigator.addView("home", MainView.class);
		this.navigator.addView("periodeView", PeriodeView.class);
		this.navigator.addView("projectLineListView", ProjectLineListView.class);
		this.navigator.addView("expenseListView", ExpenseListView.class);
		this.navigator.addView("expenseView", ExpenseView.class);
		this.navigator.addView("projectLineView", ProjectLineView.class);
		this.navigator.addView("addressSearchView", AddressSearchView.class);
		this.navigator.addView("customerView", AddressView.class);

		this.image.setSizeUndefined();
		this.horizontalLayoutTitle.addComponent(this.image);
		this.horizontalLayoutTitle.setExpandRatio(this.image, 10.0F);
		this.button.setSizeUndefined();
		this.horizontalLayoutTitle.addComponent(this.button);
		this.horizontalLayoutTitle.setComponentAlignment(this.button, Alignment.TOP_RIGHT);
		this.horizontalLayoutTitle.setExpandRatio(this.button, 10.0F);
		this.horizontalLayoutTitle.setWidth(100, Unit.PERCENTAGE);
		this.horizontalLayoutTitle.setHeight(-1, Unit.PIXELS);
		this.verticalLayout.addComponent(this.horizontalLayoutTitle);
		this.verticalLayout.setComponentAlignment(this.horizontalLayoutTitle, Alignment.MIDDLE_LEFT);
		this.container.setSizeFull();
		this.verticalLayout.addComponent(this.container);
		this.verticalLayout.setComponentAlignment(this.container, Alignment.MIDDLE_CENTER);
		this.verticalLayout.setExpandRatio(this.container, 10.0F);
		this.verticalLayout.setSizeFull();
		this.setContent(this.verticalLayout);
		this.setSizeFull();

		this.button.addClickListener(event -> this.button_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton button;
	private XdevHorizontalLayout horizontalLayoutTitle;
	private XdevImage image;
	private XdevVerticalLayout verticalLayout, container;
	private XdevAuthenticationNavigator navigator;
	// </generated-code>
}