package ch.xwr.seicentobilling.ui;

import java.util.Collection;
import java.util.List;

import org.apache.poi.ss.formula.functions.T;

import com.vaadin.data.Container;
import com.vaadin.data.util.BeanItem;
import com.xdev.ui.ItemCaptionProvider;
import com.xdev.ui.ItemIconProvider;
import com.xdev.ui.XdevSelect;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.util.KeyValueType;

public class LookupField extends XdevTextField implements XdevSelect<T> {
	private final boolean autoQueryData = false;

	/**
	 *
	 */
	public LookupField() {
		super();
		this.initUI();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.setSizeUndefined();
	} // </generated-code>

	@Override
	public void setContainerDataSource(final Class<T> beanClass, final boolean autoQueryData,
			final KeyValueType<?, ?>... nestedProperties) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setContainerDataSource(final Class<T> entityClass, final Collection<T> data,
			final KeyValueType<?, ?>... nestedProperties) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setAutoQueryData(final boolean autoQuery) {
		// TODO Auto-generated method stub

	}

	@Override
	public boolean isAutoQueryData() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public BeanItem<T> getSelectedItem() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<BeanItem<T>> getSelectedItems() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void select(final Object itemId) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setContainerDataSource(final Container newDataSource) {
		// TODO Auto-generated method stub

	}

	@Override
	public Container getContainerDataSource() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setItemCaptionFromAnnotation(final boolean itemCaptionFromAnnotation) {
		// TODO Auto-generated method stub

	}

	@Override
	public boolean isItemCaptionFromAnnotation() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void setItemCaptionValue(final String itemCaptionValue) {
		// TODO Auto-generated method stub

	}

	@Override
	public String getItemCaptionValue() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setItemCaptionProvider(final ItemCaptionProvider<T> itemCaptionProvider) {
		// TODO Auto-generated method stub

	}

	@Override
	public ItemCaptionProvider<T> getItemCaptionProvider() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setItemIconProvider(final ItemIconProvider<T> itemIconProvider) {
		// TODO Auto-generated method stub

	}

	@Override
	public ItemIconProvider<T> getItemIconProvider() {
		// TODO Auto-generated method stub
		return null;
	}

}
