package ch.xwr.seicentobilling.ui;

import com.vaadin.ui.CustomComponent;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevProgressBar;
import com.xdev.ui.XdevView;

public class ProgressView extends XdevView {

	/**
	 *
	 */
	public ProgressView() {
		super();
		this.initUI();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.progressBar = new XdevProgressBar();

		this.setCaption("Please wait");

		this.gridLayout.setColumns(2);
		this.gridLayout.setRows(2);
		this.progressBar.setSizeUndefined();
		this.gridLayout.addComponent(this.progressBar, 0, 0);
		final CustomComponent gridLayout_hSpacer = new CustomComponent();
		gridLayout_hSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_hSpacer, 1, 0, 1, 0);
		this.gridLayout.setColumnExpandRatio(1, 1.0F);
		final CustomComponent gridLayout_vSpacer = new CustomComponent();
		gridLayout_vSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_vSpacer, 0, 1, 0, 1);
		this.gridLayout.setRowExpandRatio(1, 1.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setWidth(300, Unit.PIXELS);
		this.setHeight(200, Unit.PIXELS);
	} // </generated-code>

	// <generated-code name="variables">
	private XdevProgressBar progressBar;
	private XdevGridLayout gridLayout;
	// </generated-code>

}
