
package ch.xwr.seicentobilling.dal;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;

import com.rapidclipse.framework.server.jpa.dal.JpaDataAccessObject;

import ch.xwr.seicentobilling.entities.Entity;
import ch.xwr.seicentobilling.entities.Entity_;

/**
 * Home object for domain model class Entity.
 *
 * @see Entity
 */
public class EntityDAO extends JpaDataAccessObject.Default<Entity, Long> {
	public EntityDAO() {
		super(Entity.class);
	}

	public Entity findEntity(final String name){
		return findByName(name).get(0);
	}

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<Entity> findByName(final String name) {
		final EntityManager entityManager = em();

		final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();

		final ParameterExpression<String> nameParameter = criteriaBuilder.parameter(String.class, "name");

		final CriteriaQuery<Entity> criteriaQuery = criteriaBuilder.createQuery(Entity.class);

		final Root<Entity> root = criteriaQuery.from(Entity.class);

		criteriaQuery.where(criteriaBuilder.equal(root.get(Entity_.entName), nameParameter));

		final TypedQuery<Entity> query = entityManager.createQuery(criteriaQuery);
		query.setParameter(nameParameter, name);
		return query.getResultList();
	}
}