
package ch.xwr.seicentobilling.dal;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;

import com.rapidclipse.framework.server.jpa.dal.JpaDataAccessObject;

import ch.xwr.seicentobilling.entities.Customer;
import ch.xwr.seicentobilling.entities.LabelAssignment;
import ch.xwr.seicentobilling.entities.LabelAssignment_;
import ch.xwr.seicentobilling.entities.Vat;

/**
 * Home object for domain model class Vat.
 *
 * @see Vat
 */
public class LabelAssignmentDAO extends JpaDataAccessObject.Default<LabelAssignment, Long> {
	public LabelAssignmentDAO() {
		super(LabelAssignment.class);
	}

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<LabelAssignment> findByCustomer(final Customer dao) {
		final EntityManager entityManager = em();

		final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();

		final ParameterExpression<Customer> daoParameter = criteriaBuilder.parameter(Customer.class, "dao");

		final CriteriaQuery<LabelAssignment> criteriaQuery = criteriaBuilder.createQuery(LabelAssignment.class);

		final Root<LabelAssignment> root = criteriaQuery.from(LabelAssignment.class);

		criteriaQuery.where(criteriaBuilder.equal(root.get(LabelAssignment_.customer), daoParameter));

		criteriaQuery.orderBy(criteriaBuilder.asc(root.get(LabelAssignment_.claIndex)));

		final TypedQuery<LabelAssignment> query = entityManager.createQuery(criteriaQuery);
		query.setParameter(daoParameter, dao);
		return query.getResultList();
	}
}