
package ch.xwr.seicentobilling.ui;

import java.util.Calendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.vaadin.flow.component.AttachEvent;
import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.formlayout.FormLayout.FormItem;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.tabs.Tab;
import com.vaadin.flow.component.tabs.Tabs;

import ch.xwr.seicentobilling.business.Seicento;
import ch.xwr.seicentobilling.business.TheVersion;
import ch.xwr.seicentobilling.business.auth.SeicentoUser;


public class ApplicationSettingsTabView extends VerticalLayout
{
	/** Logger initialized */
	private static final Logger LOG = LoggerFactory.getLogger(ApplicationSettingsTabView.class);
	
	private SeicentoUser currentUser;
	private Integer      index;
	
	/**
	 *
	 */
	public ApplicationSettingsTabView()
	{
		super();
		this.initUI();
		final TheVersion ver = new TheVersion();
		this.labelVersion.setText(ver.getEntryById("version"));
		this.labelArtifact.setText(ver.getEntryById("groupId") + " " + ver.getEntryById("artifactId"));

		ApplicationSettingsTabView.LOG.debug("ApplicationSettingsTabView initialized");
		this.showInfos();
		this.gridLayoutUsr.setVisible(false);
		final Map<Tab, Component> tabsToPages = new HashMap<>();
		tabsToPages.put(this.tab, this.gridLayoutApp);
		tabsToPages.put(this.tab2, this.gridLayoutUsr);
		this.tabs.setSelectedTab(this.tab);
		
		this.tabs.addSelectedChangeListener(event -> {
			tabsToPages.values().forEach(page -> page.setVisible(false));
			final Component selectedPage = tabsToPages.get(this.tabs.getSelectedTab());
			selectedPage.setVisible(true);
		});
	}
	
	private void showInfos()
	{
		final SeicentoUser su = Seicento.getSeicentoUser();
		this.currentUser = su;
		if(this.currentUser != null && this.currentUser.getClaimSet().getClaims() != null)
		{
			this.index = 0;
			
			this.currentUser.getClaimSet().getClaims().forEach((k, v) -> {
				final Label l = new Label(k + " : " + v.toString());
				this.gridLayoutUsr.add(l);
				// this.gridLayoutUsr.add(new Label(v.toString()));
				
				this.index++;
			});
		}
	}
	
	/**
	 * Event handler delegate method for the {@link VerticalLayout} {@link #gridLayoutApp}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void gridLayoutApp_onAttach(final AttachEvent event)
	{
		final Locale currentLocale = Locale.getDefault();
		this.labelCountry.setText(currentLocale.getDisplayCountry());
		this.labelLanguage.setText(currentLocale.getDisplayLanguage());
		
		final Calendar cal = Calendar.getInstance();
		this.labelTimeZone.setText(cal.getTimeZone().getID());
		
		this.labelUsername.setText(Seicento.getUserName());
		
		this.lblMemory.setText("" + Seicento.getMemory());
		this.lblSession.setText(UI.getCurrent().getSession().getState().name());
		this.lblJava.setText(System.getProperty("java.version") + " - " + System.getProperty("java.vendor"));
		this.LblOs.setText(System.getProperty("os.name") + " - " + System.getProperty("os.version") + " - "
			+ System.getProperty("os.arch"));
		
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.tabs              = new Tabs();
		this.tab2              = new Tab();
		this.tab               = new Tab();
		this.gridLayoutApp     = new VerticalLayout();
		this.horizontalLayout  = new HorizontalLayout();
		this.versionTitleLabel = new Label();
		this.labelVersion      = new Label();
		this.labelArtifact     = new Label();
		this.formLayout        = new FormLayout();
		this.formItem3         = new FormItem();
		this.label98           = new Label();
		this.labelUsername     = new Label();
		this.formItem4         = new FormItem();
		this.label97           = new Label();
		this.labelLanguage     = new Label();
		this.formItem7         = new FormItem();
		this.label96           = new Label();
		this.labelCountry      = new Label();
		this.formItem8         = new FormItem();
		this.label94           = new Label();
		this.labelTimeZone     = new Label();
		this.formItem9         = new FormItem();
		this.label93           = new Label();
		this.lblMemory         = new Label();
		this.formItem10        = new FormItem();
		this.label92           = new Label();
		this.lblSession        = new Label();
		this.formItem11        = new FormItem();
		this.label91           = new Label();
		this.lblJava           = new Label();
		this.formItem12        = new FormItem();
		this.label9            = new Label();
		this.LblOs             = new Label();
		this.gridLayoutUsr     = new VerticalLayout();

		this.setSpacing(false);
		this.setPadding(false);
		this.tab2.setLabel("User Claims");
		this.tab.setLabel("Benutzer");
		this.gridLayoutApp.setSpacing(false);
		this.gridLayoutApp.setPadding(false);
		this.versionTitleLabel.setText("Version");
		this.labelVersion.setText("0.6");
		this.labelArtifact.setText("0.6");
		this.formLayout.setResponsiveSteps(
			new FormLayout.ResponsiveStep("0px", 1, FormLayout.ResponsiveStep.LabelsPosition.TOP),
			new FormLayout.ResponsiveStep("500px", 1, FormLayout.ResponsiveStep.LabelsPosition.TOP),
			new FormLayout.ResponsiveStep("1000px", 1, FormLayout.ResponsiveStep.LabelsPosition.ASIDE));
		this.label98.setText("Username");
		this.labelUsername.setText("unknown");
		this.label97.setText("Language");
		this.labelLanguage.setText("German");
		this.label96.setText("Country");
		this.labelCountry.setText("CH");
		this.label94.setText("Time Zone");
		this.labelTimeZone.setText("unknown");
		this.label93.setText("Memory used MB");
		this.lblMemory.setText("Version");
		this.label92.setText("Session");
		this.lblSession.setText("Version");
		this.label91.setText("Java");
		this.lblJava.setText("Java");
		this.label9.setText("Operating System");
		this.LblOs.setText("Windows");

		this.tabs.add(this.tab2, this.tab);
		this.versionTitleLabel.setSizeUndefined();
		this.labelVersion.setSizeUndefined();
		this.labelArtifact.setSizeUndefined();
		this.horizontalLayout.add(this.versionTitleLabel, this.labelVersion, this.labelArtifact);
		this.label98.setSizeUndefined();
		this.label98.getElement().setAttribute("slot", "label");
		this.labelUsername.setSizeUndefined();
		this.formItem3.add(this.label98, this.labelUsername);
		this.label97.setSizeUndefined();
		this.label97.getElement().setAttribute("slot", "label");
		this.labelLanguage.setSizeUndefined();
		this.formItem4.add(this.label97, this.labelLanguage);
		this.label96.setSizeUndefined();
		this.label96.getElement().setAttribute("slot", "label");
		this.labelCountry.setSizeUndefined();
		this.formItem7.add(this.label96, this.labelCountry);
		this.label94.setSizeUndefined();
		this.label94.getElement().setAttribute("slot", "label");
		this.labelTimeZone.setSizeUndefined();
		this.formItem8.add(this.label94, this.labelTimeZone);
		this.label93.setSizeUndefined();
		this.label93.getElement().setAttribute("slot", "label");
		this.lblMemory.setSizeUndefined();
		this.formItem9.add(this.label93, this.lblMemory);
		this.label92.setSizeUndefined();
		this.label92.getElement().setAttribute("slot", "label");
		this.lblSession.setSizeUndefined();
		this.formItem10.add(this.label92, this.lblSession);
		this.label91.setSizeUndefined();
		this.label91.getElement().setAttribute("slot", "label");
		this.lblJava.setSizeUndefined();
		this.formItem11.add(this.label91, this.lblJava);
		this.label9.setSizeUndefined();
		this.label9.getElement().setAttribute("slot", "label");
		this.LblOs.setSizeUndefined();
		this.formItem12.add(this.label9, this.LblOs);
		this.formLayout.add(this.formItem3, this.formItem4, this.formItem7, this.formItem8, this.formItem9,
			this.formItem10,
			this.formItem11, this.formItem12);
		this.horizontalLayout.setWidthFull();
		this.horizontalLayout.setHeight("40px");
		this.formLayout.setWidthFull();
		this.formLayout.setHeight("50%");
		this.gridLayoutApp.add(this.horizontalLayout, this.formLayout);
		this.tabs.setWidthFull();
		this.tabs.setHeight(null);
		this.gridLayoutApp.setSizeFull();
		this.gridLayoutUsr.setWidthFull();
		this.gridLayoutUsr.setHeight("70%");
		this.add(this.tabs, this.gridLayoutApp, this.gridLayoutUsr);
		this.setSizeFull();

		this.tabs.setSelectedIndex(-1);

		this.gridLayoutApp.addAttachListener(this::gridLayoutApp_onAttach);
	} // </generated-code>

	// <generated-code name="variables">
	private FormLayout       formLayout;
	private Tab              tab2, tab;
	private HorizontalLayout horizontalLayout;
	private VerticalLayout   gridLayoutApp, gridLayoutUsr;
	private Label            versionTitleLabel, labelVersion, labelArtifact, label98, labelUsername, label97,
		labelLanguage,
		label96, labelCountry, label94, labelTimeZone, label93, lblMemory, label92, lblSession, label91, lblJava,
		label9,
		LblOs;
	private Tabs             tabs;
	private FormItem         formItem3, formItem4, formItem7, formItem8, formItem9, formItem10, formItem11, formItem12;
	// </generated-code>

}
