
package ch.xwr.seicentobilling.ui;

import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.formlayout.FormLayout.FormItem;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.PasswordField;


public class CompanyTab1 extends VerticalLayout
{

	/**
	 *
	 */
	public CompanyTab1()
	{
		super();
		this.initUI();
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.formLayout      = new FormLayout();
		this.formItem11      = new FormItem();
		this.cboCmpAbaActive = new Checkbox();
		this.formItem        = new FormItem();
		this.label           = new Label();
		this.passwordField   = new PasswordField();

		this.formLayout.setMinHeight("100%");
		this.formLayout.setMinWidth("100%");
		this.formLayout.setResponsiveSteps(
			new FormLayout.ResponsiveStep("0px", 1, FormLayout.ResponsiveStep.LabelsPosition.TOP),
			new FormLayout.ResponsiveStep("500px", 2, FormLayout.ResponsiveStep.LabelsPosition.TOP),
			new FormLayout.ResponsiveStep("1000px", 3, FormLayout.ResponsiveStep.LabelsPosition.ASIDE));
		this.cboCmpAbaActive.setLabel("Schnittstelle Aktiv");
		this.label.setText("Label");

		this.cboCmpAbaActive.setWidthFull();
		this.cboCmpAbaActive.setHeight(null);
		this.formItem11.add(this.cboCmpAbaActive);
		this.label.setSizeUndefined();
		this.label.getElement().setAttribute("slot", "label");
		this.passwordField.setWidthFull();
		this.passwordField.setHeight(null);
		this.formItem.add(this.label, this.passwordField);
		this.formLayout.add(this.formItem11, this.formItem);
		this.formLayout.setWidth("100px");
		this.formLayout.setHeight("100px");
		this.add(this.formLayout);
		this.setSizeFull();
	} // </generated-code>
	
	// <generated-code name="variables">
	private FormLayout    formLayout;
	private Checkbox      cboCmpAbaActive;
	private PasswordField passwordField;
	private Label         label;
	private FormItem      formItem11, formItem;
	// </generated-code>
	
}
