
package ch.xwr.seicentobilling.ui;

import java.net.MalformedURLException;
import java.net.URL;

import org.jfree.util.Log;

import com.rapidclipse.framework.server.data.renderer.RenderedComponent;
import com.vaadin.flow.component.html.Anchor;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;

import ch.xwr.seicentobilling.entities.Activity;


public class FunctionActHyperlink extends HorizontalLayout implements RenderedComponent<Activity>
{

	/**
	 *
	 */
	public FunctionActHyperlink()
	{
		super();
		this.initUI();
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.icon   = new Icon(VaadinIcon.BOLT);
		this.anchor = new Anchor();
		
		this.setSpacing(false);
		this.anchor.setText("Link");
		
		this.anchor.setSizeUndefined();
		this.add(this.icon, this.anchor);
		this.setSizeUndefined();
	} // </generated-code>

	@Override
	public void renderComponent(final Activity value)
	{
		if(value.getActLink() != null)
		{
			final String link = this.getWebLink(value.getActLink());
			this.anchor.setTitle(link);
			if(value.getActLink().isEmpty())
			{
				this.setEnabled(false);
			}
			this.anchor.setHref(link);
			this.anchor.setTarget("_blank");
		}
		else
		{
			this.setEnabled(false);
		}
		
	}

	private String getWebLink(String cnkLink)
	{
		try
		{
			final URL myUrl = new URL(cnkLink);
			return myUrl.toString();
		}
		catch(final MalformedURLException e)
		{
			Log.error(e);
		}

		cnkLink = "https://" + cnkLink;
		return cnkLink;
	}
	
	// <generated-code name="variables">
	private Anchor anchor;
	private Icon   icon;
	// </generated-code>
	
}
