
package ch.xwr.seicentobilling.ui;

import com.vaadin.flow.component.dependency.HtmlImport;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;


@Route(value = "view2", layout = MainContainer.class)
@HtmlImport("frontend://styles/shared-styles.html")
public class View2 extends VerticalLayout
{
	
	/**
	 *
	 */
	public View2()
	{
		super();
		this.initUI();
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.lblContent = new Label();
		
		this.lblContent.setText("view 2");
		this.lblContent.getStyle().set("font-size", "3em");
		
		this.lblContent.setSizeUndefined();
		this.add(this.lblContent);
		this.setSizeFull();
	} // </generated-code>
	
	// <generated-code name="variables">
	private Label lblContent;
	// </generated-code>
	
}
