
package ch.xwr.seicentobilling.ui.crm;

import com.flowingcode.vaadin.addons.ironicons.IronIcons;
import com.rapidclipse.framework.server.resources.CaptionUtils;
import com.rapidclipse.framework.server.resources.StringResourceUtils;
import com.rapidclipse.framework.server.ui.ItemLabelGeneratorFactory;
import com.rapidclipse.framework.server.ui.StartsWithIgnoreCaseItemFilter;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.formlayout.FormLayout.FormItem;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.data.binder.BeanValidationBinder;
import com.vaadin.flow.data.provider.DataProvider;

import ch.xwr.seicentobilling.business.LovCrm;
import ch.xwr.seicentobilling.business.RowObjectManager;
import ch.xwr.seicentobilling.business.helper.SeicentoCrud;
import ch.xwr.seicentobilling.dal.ContactRelationDAO;
import ch.xwr.seicentobilling.dal.CustomerDAO;
import ch.xwr.seicentobilling.entities.ContactRelation;
import ch.xwr.seicentobilling.entities.Customer;
import ch.xwr.seicentobilling.ui.SeicentoNotification;


public class ContactRelationPopup extends VerticalLayout
{
	
	public ContactRelationPopup()
	{
		super();
		this.initUI();

		this.cbxRelationOne.setItems(LovCrm.ContactRelation.values());
		this.cbxRelationTwo.setItems(LovCrm.ContactRelation.values());
		
		// get Parameter
		final Long      beanId = (Long)UI.getCurrent().getSession().getAttribute("beanId");
		final Long      objId  = (Long)UI.getCurrent().getSession().getAttribute("objId");
		ContactRelation bean   = null;
		Customer        obj    = null;
		if(beanId == null)
		{
			final CustomerDAO cusDao = new CustomerDAO();
			obj = cusDao.find(objId);
			
			bean = new ContactRelation();
			bean.setCustomerOne(obj);
			
		}
		else
		{
			// final CustomerLinkDAO dao = new CustomerLinkDAO();
			// bean = dao.find(beanId.longValue());
			// ignore - only new allowed
		}
		
		this.setBeanGui(bean);
		
	}
	
	private void setBeanGui(final ContactRelation bean)
	{
		// set Bean + Fields
		this.binder.setBean(bean);
		
		// set RO Fields
		this.setROFields();
		
		// postLoadAccountAction(bean);
		// this.txtExpText.focus();
	}
	
	private void setROFields()
	{
		this.cmbCustomerOne.setEnabled(false);
		// this.cbxRelationTwo.setEnabled(false);
	}
	
	public static Dialog getPopupWindow()
	{
		final Dialog win = new Dialog();
		win.setSizeFull();
		win.setModal(true);
		win.setResizable(true);
		final Button cancelButton = new Button("", e -> {
			win.close();
		});
		cancelButton.setIcon(VaadinIcon.CLOSE.create());
		cancelButton.getStyle().set("float", "right");
		win.add(cancelButton, new ContactRelationPopup());
		return win;
	}
	
	/**
	 * Event handler delegate method for the {@link Button} {@link #cmdReset}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdReset_onClick(final ClickEvent<Button> event)
	{
		UI.getCurrent().getSession().setAttribute(String.class, "cmdCancel");
		this.binder.removeBean();
		((Dialog)this.getParent().get()).close();
	}
	
	/**
	 * Event handler delegate method for the {@link Button} {@link #cmdSave}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_onClick(final ClickEvent<Button> event)
	{
		UI.getCurrent().getSession().setAttribute(String.class, "cmdSave");
		
		if(SeicentoCrud.doSave(this.binder, new ContactRelationDAO()))
		{
			try
			{
				final RowObjectManager man = new RowObjectManager();
				man.updateObject(this.binder.getBean().getCorId(),
					this.binder.getBean().getClass().getSimpleName());
				
				((Dialog)this.getParent().get()).close();
				SeicentoNotification.showInfo("Daten wurden gespeichert");
			}
			catch(final Exception e)
			{
				SeicentoNotification.showError(e.getMessage());
				e.printStackTrace();
			}
		}
		
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.verticalLayout    = new VerticalLayout();
		this.horizontalLayout  = new HorizontalLayout();
		this.label             = new Label();
		this.formLayout        = new FormLayout();
		this.formItem2         = new FormItem();
		this.lblCustomerOne    = new Label();
		this.cmbCustomerOne    = new ComboBox<>();
		this.formItem6         = new FormItem();
		this.lblCorTypeOne     = new Label();
		this.cbxRelationOne    = new ComboBox<>();
		this.formItem          = new FormItem();
		this.lblCustomerTwo    = new Label();
		this.cmbCustomerTwo    = new ComboBox<>();
		this.formItem3         = new FormItem();
		this.lblCorTypeTwo     = new Label();
		this.cbxRelationTwo    = new ComboBox<>();
		this.horizontalLayout2 = new HorizontalLayout();
		this.cmdSave           = new Button();
		this.cmdReset          = new Button();
		this.binder            = new BeanValidationBinder<>(ContactRelation.class);

		this.label.setText("Beziehungen");
		this.formLayout.setResponsiveSteps(
			new FormLayout.ResponsiveStep("0px", 1, FormLayout.ResponsiveStep.LabelsPosition.TOP),
			new FormLayout.ResponsiveStep("500px", 2, FormLayout.ResponsiveStep.LabelsPosition.TOP),
			new FormLayout.ResponsiveStep("1000px", 3, FormLayout.ResponsiveStep.LabelsPosition.ASIDE));
		this.lblCustomerOne.setText("CustomerOne");
		this.cmbCustomerOne.setDataProvider(
			StartsWithIgnoreCaseItemFilter.New(this.cmbCustomerOne::getItemLabelGenerator),
			DataProvider.ofCollection(new CustomerDAO().findAll()));
		this.cmbCustomerOne.setItemLabelGenerator(ItemLabelGeneratorFactory.NonNull(Customer::getShortname));
		this.lblCorTypeOne.setText("RelationOne");
		this.cbxRelationOne.setItemLabelGenerator(ItemLabelGeneratorFactory.NonNull(CaptionUtils::resolveCaption));
		this.lblCustomerTwo.setText("CustomerTwo");
		this.cmbCustomerTwo.setDataProvider(
			StartsWithIgnoreCaseItemFilter.New(this.cmbCustomerTwo::getItemLabelGenerator),
			DataProvider.ofCollection(new CustomerDAO().findAll()));
		this.cmbCustomerTwo.setItemLabelGenerator(ItemLabelGeneratorFactory.NonNull(Customer::getShortname));
		this.lblCorTypeTwo.setText("RelationTwo");
		this.cbxRelationTwo.setItemLabelGenerator(ItemLabelGeneratorFactory.NonNull(CaptionUtils::resolveCaption));
		this.cmdSave.setText(StringResourceUtils.optLocalizeString("{$cmdSave.caption}", this));
		this.cmdSave.setIcon(IronIcons.SAVE.create());
		this.cmdReset.setText(StringResourceUtils.optLocalizeString("{$cmdReset.caption}", this));
		this.cmdReset.setIcon(IronIcons.CANCEL.create());

		this.label.setSizeUndefined();
		this.horizontalLayout.add(this.label);
		this.horizontalLayout.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.label);
		this.lblCustomerOne.setSizeUndefined();
		this.lblCustomerOne.getElement().setAttribute("slot", "label");
		this.cmbCustomerOne.setWidthFull();
		this.cmbCustomerOne.setHeight(null);
		this.formItem2.add(this.lblCustomerOne, this.cmbCustomerOne);
		this.lblCorTypeOne.setSizeUndefined();
		this.lblCorTypeOne.getElement().setAttribute("slot", "label");
		this.cbxRelationOne.setWidthFull();
		this.cbxRelationOne.setHeight(null);
		this.formItem6.add(this.lblCorTypeOne, this.cbxRelationOne);
		this.lblCustomerTwo.setSizeUndefined();
		this.lblCustomerTwo.getElement().setAttribute("slot", "label");
		this.cmbCustomerTwo.setWidthFull();
		this.cmbCustomerTwo.setHeight(null);
		this.formItem.add(this.lblCustomerTwo, this.cmbCustomerTwo);
		this.lblCorTypeTwo.setSizeUndefined();
		this.lblCorTypeTwo.getElement().setAttribute("slot", "label");
		this.cbxRelationTwo.setWidthFull();
		this.cbxRelationTwo.setHeight(null);
		this.formItem3.add(this.lblCorTypeTwo, this.cbxRelationTwo);
		this.formLayout.add(this.formItem2, this.formItem6, this.formItem, this.formItem3);
		this.cmdSave.setSizeUndefined();
		this.cmdReset.setSizeUndefined();
		this.horizontalLayout2.add(this.cmdSave, this.cmdReset);
		this.horizontalLayout.setWidthFull();
		this.horizontalLayout.setHeight("30px");
		this.formLayout.setSizeFull();
		this.horizontalLayout2.setWidthFull();
		this.horizontalLayout2.setHeight("12%");
		this.verticalLayout.add(this.horizontalLayout, this.formLayout, this.horizontalLayout2);
		this.verticalLayout.setSizeFull();
		this.add(this.verticalLayout);
		this.setSizeFull();

		this.cmdSave.addClickListener(this::cmdSave_onClick);
		this.cmdReset.addClickListener(this::cmdReset_onClick);
	} // </generated-code>

	// <generated-code name="variables">
	private FormLayout                                                       formLayout;
	private BeanValidationBinder<ContactRelation>                            binder;
	private Button                                                           cmdSave, cmdReset;
	private ComboBox<Customer>                                               cmbCustomerOne, cmbCustomerTwo;
	private VerticalLayout                                                   verticalLayout;
	private HorizontalLayout                                                 horizontalLayout, horizontalLayout2;
	private Label                                                            label, lblCustomerOne, lblCorTypeOne,
		lblCustomerTwo, lblCorTypeTwo;
	private ComboBox<ch.xwr.seicentobilling.business.LovCrm.ContactRelation> cbxRelationOne, cbxRelationTwo;
	private FormItem                                                         formItem2, formItem6, formItem, formItem3;
	// </generated-code>
	
}
