
package ch.xwr.seicentobilling.ui.crm;

import com.vaadin.flow.component.html.Image;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;


public class FunctionAddressHyperlink extends VerticalLayout
{
	
	/**
	 *
	 */
	public FunctionAddressHyperlink()
	{
		super();
		this.initUI();
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.linkMaps = new Image();

		this.linkMaps.setText("Link to Google Maps");
		this.linkMaps.setSrc("images/gmaps32.PNG");

		this.linkMaps.setSizeUndefined();
		this.add(this.linkMaps);
		this.setSizeFull();
	} // </generated-code>
	
	// <generated-code name="variables">
	private Image linkMaps;
	// </generated-code>

}
