
package ch.xwr.seicentobilling.ui.crm;

import java.io.File;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.flowingcode.vaadin.addons.ironicons.IronIcons;
import com.rapidclipse.framework.server.resources.CaptionUtils;
import com.rapidclipse.framework.server.ui.ItemLabelGeneratorFactory;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.splitlayout.SplitLayout;
import com.vaadin.flow.component.treegrid.TreeGrid;

import ch.xwr.seicentobilling.business.crm.CrmExcelHandler;
import ch.xwr.seicentobilling.business.crm.CustomerDto;
import ch.xwr.seicentobilling.business.model.generic.FileUploadDto;


public class ImportContactsPopup extends VerticalLayout
{
	/** Logger initialized */
	private static final Logger LOG = LoggerFactory.getLogger(ImportContactsPopup.class);

	public static enum ImportType
	{
		excel,
		vcard
	}

	protected FileUploadDto result;
	
	/**
	 *
	 */
	public ImportContactsPopup()
	{
		super();
		this.initUI();
		this.labelSize.setText("");
		this.labelResult.setText("");
		this.labelType.setText("Zum Hochladen, bitte Dateityp wählen");
		this.labelHeader.setText("");
		this.labelFileName.setText("");

		this.comboBoxType.setItems(ImportType.values());
		// this.comboBoxType.setValue(ImportType.excel); //trigger event

		// setupUploader();
		this.cmdStartImport.setEnabled(false);
		this.cmdSave.setEnabled(false);
		this.cmdSelect.setEnabled(false);
	}
	
	private void processUploadedFile(final File outFile)
	{
		final CrmExcelHandler   exc = new CrmExcelHandler();
		final List<CustomerDto> lst = exc.readContactsToList(outFile);

		if(!lst.isEmpty())
		{
			this.labelSize.setText("Zeilen: " + lst.size());
		}

		outFile.delete();

	}

	public static Dialog getPopupWindow()
	{
		final Dialog win = new Dialog();
		// win.setSizeFull();
		win.setModal(true);
		win.setResizable(true);
		final Button cancelButton = new Button("", e -> {
			win.close();
		});
		// win.setWidth("760");
		// win.setHeight("300");
		cancelButton.setIcon(VaadinIcon.CLOSE.create());
		cancelButton.getStyle().set("float", "right");
		win.add(cancelButton, new ImportContactsPopup());
		return win;
	}
	
	/**
	 * Event handler delegate method for the {@link Button} {@link #cmdSave}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_onClick(final ClickEvent<Button> event)
	{
		UI.getCurrent().getSession().setAttribute(String.class, "cmdSave");
		final CrmExcelHandler exc     = new CrmExcelHandler();
		final int             icount  = 0;
		final int             ierror  = 0;
		final int             iselect = 0;

		ImportContactsPopup.LOG.info("Start saving list to Database");

		ImportContactsPopup.LOG.info("Liste erfolgreich importiert");
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.splitLayout            = new SplitLayout();
		this.verticalLayout         = new VerticalLayout();
		this.horizontalLayout       = new HorizontalLayout();
		this.icon                   = new Icon(VaadinIcon.FILE_TABLE);
		this.titlelabel             = new Label();
		this.verticalLayout2        = new VerticalLayout();
		this.horizontalLayout6      = new HorizontalLayout();
		this.comboBoxType           = new ComboBox<>();
		this.horizontalLayout7      = new HorizontalLayout();
		this.labelType              = new Label();
		this.buttonHorizontalLayout = new HorizontalLayout();
		this.cmdStartImport         = new Button();
		this.labelFileName          = new Label();
		this.horizontalLayout4      = new HorizontalLayout();
		this.labelSize              = new Label();
		this.horizontalLayout2      = new HorizontalLayout();
		this.cmdSelect              = new Button();
		this.cmdSave                = new Button();
		this.cmdReset               = new Button();
		this.horizontalLayout3      = new HorizontalLayout();
		this.labelResult            = new Label();
		this.labelHeader            = new Label();
		this.treeGrid               = new TreeGrid<>();
		
		this.splitLayout.setOrientation(SplitLayout.Orientation.VERTICAL);
		this.titlelabel.setText("Import Datei");
		this.verticalLayout2.setPadding(false);
		this.comboBoxType.setItemLabelGenerator(ItemLabelGeneratorFactory.NonNull(CaptionUtils::resolveCaption));
		this.labelType.setText("Label");
		this.cmdStartImport.setText("Importieren");
		this.cmdStartImport.setIcon(VaadinIcon.ROCKET.create());
		this.labelFileName.setText("Label");
		this.labelSize.setText("Label");
		this.cmdSelect.setText("Select/Unselect");
		this.cmdSelect.setIcon(IronIcons.CHECK_BOX.create());
		this.cmdSave.setText("Speichern");
		this.cmdSave.setIcon(IronIcons.SAVE.create());
		this.cmdReset.setText("Schliessen");
		this.cmdReset.setIcon(VaadinIcon.CLOSE_SMALL.create());
		this.labelResult.setText("Label");
		this.labelHeader.setText(
			"CAM1;CAM2;Nachname;Vorname;Firma;x;Adresse;PLZ;Ort;;TelefonG;Mobile;TelefonP;x;E-Mail;Webseite;x;Newsletter;X-Mas;Verwendung;Notizen");
		this.labelHeader.getStyle().set("font-size", "10px");
		this.treeGrid.setSelectionMode(Grid.SelectionMode.SINGLE);
		
		this.titlelabel.setSizeUndefined();
		this.horizontalLayout.add(this.icon, this.titlelabel);
		this.horizontalLayout.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.icon);
		this.horizontalLayout.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.titlelabel);
		this.comboBoxType.setWidth(null);
		this.comboBoxType.setHeight("44px");
		this.horizontalLayout7.setWidth("500px");
		this.horizontalLayout7.setHeight("40px");
		this.labelType.setWidth("270px");
		this.labelType.setHeight("40px");
		this.horizontalLayout6.add(this.comboBoxType, this.horizontalLayout7, this.labelType);
		this.horizontalLayout6.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.labelType);
		this.horizontalLayout6.setFlexGrow(1.0, this.labelType);
		this.cmdStartImport.setWidth("25%");
		this.cmdStartImport.setHeight(null);
		this.labelFileName.setWidth("100px");
		this.labelFileName.setHeight("40px");
		this.horizontalLayout4.setWidth("500px");
		this.horizontalLayout4.setHeight("20px");
		this.labelSize.setWidth("300px");
		this.labelSize.setHeight("40px");
		this.buttonHorizontalLayout.add(this.cmdStartImport, this.labelFileName, this.horizontalLayout4,
			this.labelSize);
		this.buttonHorizontalLayout.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.cmdStartImport);
		this.horizontalLayout6.setWidthFull();
		this.horizontalLayout6.setHeight("60px");
		this.buttonHorizontalLayout.setWidthFull();
		this.buttonHorizontalLayout.setHeight("60px");
		this.verticalLayout2.add(this.horizontalLayout6, this.buttonHorizontalLayout);
		this.cmdSelect.setWidth("30%");
		this.cmdSelect.setHeight(null);
		this.cmdSave.setWidth("25%");
		this.cmdSave.setHeight(null);
		this.cmdReset.setWidth("25%");
		this.cmdReset.setHeight(null);
		this.horizontalLayout3.setWidth("91px");
		this.horizontalLayout3.setHeight("30px");
		this.labelResult.setWidth("280px");
		this.labelResult.setHeightFull();
		this.horizontalLayout2.add(this.cmdSelect, this.cmdSave, this.cmdReset, this.horizontalLayout3,
			this.labelResult);
		this.horizontalLayout2.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.cmdSelect);
		this.horizontalLayout2.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.cmdSave);
		this.horizontalLayout2.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.cmdReset);
		this.horizontalLayout.setWidthFull();
		this.horizontalLayout.setHeight("30px");
		this.verticalLayout2.setWidthFull();
		this.verticalLayout2.setHeight(null);
		this.horizontalLayout2.setWidthFull();
		this.horizontalLayout2.setHeight("60px");
		this.labelHeader.setWidthFull();
		this.labelHeader.setHeight(null);
		this.verticalLayout.add(this.horizontalLayout, this.verticalLayout2, this.horizontalLayout2, this.labelHeader);
		this.splitLayout.addToPrimary(this.verticalLayout);
		this.splitLayout.addToSecondary(this.treeGrid);
		this.splitLayout.setSplitterPosition(50.0);
		this.splitLayout.setSizeFull();
		this.add(this.splitLayout);
		this.setFlexGrow(1.0, this.splitLayout);
		this.setSizeFull();
		
		this.cmdSave.addClickListener(this::cmdSave_onClick);
	} // </generated-code>

	// <generated-code name="variables">
	private ComboBox<ImportType> comboBoxType;
	private Button               cmdStartImport, cmdSelect, cmdSave, cmdReset;
	private TreeGrid<?>          treeGrid;
	private SplitLayout          splitLayout;
	private VerticalLayout       verticalLayout, verticalLayout2;
	private HorizontalLayout     horizontalLayout, horizontalLayout6, horizontalLayout7, buttonHorizontalLayout,
		horizontalLayout4, horizontalLayout2, horizontalLayout3;
	private Label                titlelabel, labelType, labelFileName, labelSize, labelResult, labelHeader;
	private Icon                 icon;
	// </generated-code>

}
