
package ch.xwr.seicentobilling.ui.crm;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import com.flowingcode.vaadin.addons.ironicons.IronIcons;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.html.Anchor;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.server.StreamResource;

import ch.xwr.seicentobilling.business.crm.VcardHandler;
import ch.xwr.seicentobilling.dal.CustomerDAO;
import ch.xwr.seicentobilling.entities.Customer;


public class VcardPopup extends VerticalLayout
{
	Customer             bean  = null;
	private VcardHandler vcard = null;

	/**
	 *
	 */
	public VcardPopup()
	{
		super();
		this.initUI();

		// get Parameter
		final Long beanId = (Long)UI.getCurrent().getSession().getAttribute("cusbeanId");
		if(beanId != null)
		{
			final CustomerDAO dao = new CustomerDAO();
			this.bean = dao.find(beanId.longValue());
		}
		else
		{
			// close/disable
			this.cmdCreate.setEnabled(false);
		}
		
		this.lblFileName.setText("");
		this.cmdDownload.setEnabled(false);
	}

	public static Dialog getPopupWindow()
	{
		final Dialog win = new Dialog();
		win.setSizeFull();
		win.setModal(true);
		win.setResizable(true);
		final Button cancelButton = new Button("", e -> {
			win.close();
		});
		cancelButton.setIcon(VaadinIcon.CLOSE.create());
		cancelButton.getStyle().set("float", "right");
		win.add(cancelButton, new VcardPopup());
		return win;
	}

	/**
	 * Event handler delegate method for the {@link Button} {@link #cmdCreate}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdCreate_onClick(final ClickEvent<Button> event)
	{
		this.vcard = new VcardHandler(this.bean, ".vcf");
		this.vcard.generateVcard();
		this.cmdDownload.setEnabled(true);

		final StreamResource resource = new StreamResource(this.vcard.getFile().getName(),
			() -> this.createExport(this.vcard.getFile()));

		this.downloadLink.setHref(resource);
		this.downloadLink.setEnabled(true);

		this.lblFileName.setText(this.vcard.getFile().getAbsoluteFile().getName());
	}

	private InputStream createExport(final File fiv)
	{
		FileInputStream inStream = null;
		try
		{
			inStream = new FileInputStream(fiv);
		}
		catch(final IOException e)
		{
			e.printStackTrace();
			return null;
		}
		return inStream;
	}

	/**
	 * Event handler delegate method for the {@link Button} {@link #cmdCancel}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdCancel_onClick(final ClickEvent<Button> event)
	{
		UI.getCurrent().getSession().setAttribute(String.class, "cmdCancel");

		((Dialog)this.getParent().get()).close();
	}
	
	/**
	 * Event handler delegate method for the {@link Button} {@link #cmdDownload}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdDownload_onClick(final ClickEvent<Button> event)
	{

	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.verticalLayout    = new VerticalLayout();
		this.horizontalLayout  = new HorizontalLayout();
		this.icon              = new Icon(VaadinIcon.FILE_TEXT_O);
		this.label             = new Label();
		this.verticalLayout2   = new VerticalLayout();
		this.textArea          = new TextArea();
		this.horizontalLayout3 = new HorizontalLayout();
		this.label2            = new Label();
		this.lblFileName       = new Label();
		this.horizontalLayout2 = new HorizontalLayout();
		this.cmdCreate         = new Button();
		this.downloadLink      = new Anchor();
		this.cmdDownload       = new Button();
		this.cmdCancel         = new Button();

		this.label.setText("Vcard erstellen");
		this.textArea.setValue(
			"Die Funktion ermöglicht das Erstellen einer elektronischen Visitenkarte (vcard) des aktuellen Kontakts. Die erstellte Datei kann in verschiedenen Programmen (Mobile, Outlook etc.) importiert werden.");
		this.label2.setText("Datei");
		this.lblFileName.setText("Label");
		this.cmdCreate.setText("Erstellen");
		this.cmdCreate.setIcon(VaadinIcon.FILE_TEXT_O.create());
		this.downloadLink.setEnabled(false);
		this.downloadLink.setText("Downlod");
		this.cmdDownload.setEnabled(false);
		this.cmdDownload.setText("Download");
		this.cmdDownload.setVisible(false);
		this.cmdDownload.setDisableOnClick(true);
		this.cmdDownload.setIcon(VaadinIcon.DOWNLOAD.create());
		this.cmdCancel.setText("Schliessen");
		this.cmdCancel.setIcon(IronIcons.CLOSE.create());

		this.label.setSizeUndefined();
		this.horizontalLayout.add(this.icon, this.label);
		this.horizontalLayout.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.label);
		this.textArea.setWidthFull();
		this.textArea.setHeight("91px");
		this.verticalLayout2.add(this.textArea);
		this.label2.setSizeUndefined();
		this.lblFileName.setSizeUndefined();
		this.horizontalLayout3.add(this.label2, this.lblFileName);
		this.cmdCreate.setSizeUndefined();
		this.downloadLink.setSizeUndefined();
		this.cmdDownload.setSizeUndefined();
		this.cmdCancel.setSizeUndefined();
		this.horizontalLayout2.add(this.cmdCreate, this.downloadLink, this.cmdDownload, this.cmdCancel);
		this.horizontalLayout.setWidthFull();
		this.horizontalLayout.setHeight("30px");
		this.verticalLayout2.setWidthFull();
		this.verticalLayout2.setHeight("140px");
		this.horizontalLayout3.setWidthFull();
		this.horizontalLayout3.setHeight("40px");
		this.horizontalLayout2.setWidthFull();
		this.horizontalLayout2.setHeight("12%");
		this.verticalLayout.add(this.horizontalLayout, this.verticalLayout2, this.horizontalLayout3,
			this.horizontalLayout2);
		this.verticalLayout.setWidth("600px");
		this.verticalLayout.setHeight("350px");
		this.add(this.verticalLayout);
		this.setSizeFull();

		this.cmdCreate.addClickListener(this::cmdCreate_onClick);
		this.cmdDownload.addClickListener(this::cmdDownload_onClick);
		this.cmdCancel.addClickListener(this::cmdCancel_onClick);
	} // </generated-code>
	
	// <generated-code name="variables">
	private Button           cmdCreate, cmdDownload, cmdCancel;
	private Anchor           downloadLink;
	private TextArea         textArea;
	private VerticalLayout   verticalLayout, verticalLayout2;
	private HorizontalLayout horizontalLayout, horizontalLayout3, horizontalLayout2;
	private Label            label, label2, lblFileName;
	private Icon             icon;
	// </generated-code>
	
}
