package ch.xwr.seicentobilling.ui.desktop.crm;

import com.vaadin.event.ShortcutAction;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.xdev.dal.DAOs;
import com.xdev.res.ApplicationResource;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevFieldGroup;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevPanel;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.combobox.XdevComboBox;

import ch.xwr.seicentobilling.business.LovCrm;
import ch.xwr.seicentobilling.business.RowObjectManager;
import ch.xwr.seicentobilling.dal.CustomerDAO;
import ch.xwr.seicentobilling.entities.ContactRelation;
import ch.xwr.seicentobilling.entities.ContactRelation_;
import ch.xwr.seicentobilling.entities.Customer;

public class ContactRelationPopup extends XdevView {

	/**
	 *
	 */
	public ContactRelationPopup() {
		super();
		this.initUI();

		// State
		this.cbxRelationOne.addItems((Object[]) LovCrm.ContactRelation.values());
		this.cbxRelationTwo.addItems((Object[]) LovCrm.ContactRelation.values());

		// get Parameter
		final Long beanId = (Long) UI.getCurrent().getSession().getAttribute("beanId");
		final Long objId = (Long) UI.getCurrent().getSession().getAttribute("objId");
		ContactRelation bean = null;
		Customer obj = null;

		if (beanId == null) {
			final CustomerDAO cusDao = new CustomerDAO();
			obj = cusDao.find(objId);

			bean = new ContactRelation();
			bean.setCustomerOne(obj);


		} else {
//			final CustomerLinkDAO dao = new CustomerLinkDAO();
//			bean = dao.find(beanId.longValue());
			//ignore - only new allowed
		}

		setBeanGui(bean);

	}

	private void setBeanGui(final ContactRelation bean) {
		// set Bean + Fields
		this.fieldGroup.setItemDataSource(bean);

		// set RO Fields
		setROFields();

		//postLoadAccountAction(bean);
		//this.txtExpText.focus();
	}


	private void setROFields() {
		this.cmbCustomerOne.setEnabled(false);
		//this.cbxRelationTwo.setEnabled(false);
	}

	public static Window getPopupWindow() {
		final Window win = new Window();
		win.setWidth("720");
		win.setHeight("400");
		win.center();
		win.setModal(true);
		win.setContent(new ContactRelationPopup());

		return win;
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdSave}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_buttonClick(final Button.ClickEvent event) {
		UI.getCurrent().getSession().setAttribute(String.class, "cmdSave");

		try {
			this.fieldGroup.save();
			final RowObjectManager man = new RowObjectManager();
			man.updateObject(this.fieldGroup.getItemDataSource().getBean().getCorId(),
					this.fieldGroup.getItemDataSource().getBean().getClass().getSimpleName());

			((Window) this.getParent()).close();
			Notification.show("Save clicked", "Daten wurden gespeichert", Notification.Type.TRAY_NOTIFICATION);
		} catch (final Exception e) {
			Notification.show("Fehler beim Speichern", e.getMessage(), Notification.Type.ERROR_MESSAGE);
			e.printStackTrace();
		}

	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdReset}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdReset_buttonClick(final Button.ClickEvent event) {
		this.fieldGroup.discard();
		((Window) this.getParent()).close();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.panel = new XdevPanel();
		this.form = new XdevGridLayout();
		this.lblCustomerOne = new XdevLabel();
		this.cmbCustomerOne = new XdevComboBox<>();
		this.lblCorTypeOne = new XdevLabel();
		this.cbxRelationOne = new XdevComboBox<>();
		this.lblCustomerTwo = new XdevLabel();
		this.cmbCustomerTwo = new XdevComboBox<>();
		this.lblCorTypeTwo = new XdevLabel();
		this.cbxRelationTwo = new XdevComboBox<>();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.cmdSave = new XdevButton();
		this.cmdReset = new XdevButton();
		this.fieldGroup = new XdevFieldGroup<>(ContactRelation.class);

		this.setCaption("CustomerLink");
		this.panel.setCaption("Beziehungen");
		this.panel.setTabIndex(0);
		this.form.setCaption("CustomerLink");
		this.lblCustomerOne.setValue("CustomerOne");
		this.cmbCustomerOne.setItemCaptionFromAnnotation(false);
		this.cmbCustomerOne.setContainerDataSource(Customer.class, DAOs.get(CustomerDAO.class).findAll());
		this.cmbCustomerOne.setItemCaptionPropertyId("shortname");
		this.lblCorTypeOne.setValue("RelationOne");
		this.lblCustomerTwo.setValue("CustomerTwo");
		this.cmbCustomerTwo.setItemCaptionFromAnnotation(false);
		this.cmbCustomerTwo.setContainerDataSource(Customer.class, DAOs.get(CustomerDAO.class).findAll());
		this.cmbCustomerTwo.setItemCaptionPropertyId("shortname");
		this.lblCorTypeTwo.setValue("RelationTwo");
		this.horizontalLayout.setMargin(new MarginInfo(true, false, true, false));
		this.cmdSave.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/save1.png"));
		this.cmdSave.setCaption("Speichern");
		this.cmdSave.setClickShortcut(ShortcutAction.KeyCode.ENTER);
		this.cmdReset.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/cancel1.png"));
		this.cmdReset.setCaption("Abbrechen");
		this.cmdReset.setClickShortcut(ShortcutAction.KeyCode.ESCAPE);
		this.fieldGroup.bind(this.cbxRelationOne, ContactRelation_.corTypeOne.getName());
		this.fieldGroup.bind(this.cbxRelationTwo, ContactRelation_.corTypeTwo.getName());
		this.fieldGroup.bind(this.cmbCustomerOne, ContactRelation_.customerOne.getName());
		this.fieldGroup.bind(this.cmbCustomerTwo, ContactRelation_.customerTwo.getName());

		this.cmdSave.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdSave);
		this.horizontalLayout.setComponentAlignment(this.cmdSave, Alignment.MIDDLE_LEFT);
		this.cmdReset.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdReset);
		this.horizontalLayout.setComponentAlignment(this.cmdReset, Alignment.MIDDLE_LEFT);
		this.form.setColumns(2);
		this.form.setRows(6);
		this.lblCustomerOne.setSizeUndefined();
		this.form.addComponent(this.lblCustomerOne, 0, 0);
		this.cmbCustomerOne.setWidth(100, Unit.PERCENTAGE);
		this.cmbCustomerOne.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.cmbCustomerOne, 1, 0);
		this.lblCorTypeOne.setSizeUndefined();
		this.form.addComponent(this.lblCorTypeOne, 0, 1);
		this.cbxRelationOne.setSizeUndefined();
		this.form.addComponent(this.cbxRelationOne, 1, 1);
		this.lblCustomerTwo.setSizeUndefined();
		this.form.addComponent(this.lblCustomerTwo, 0, 2);
		this.cmbCustomerTwo.setWidth(100, Unit.PERCENTAGE);
		this.cmbCustomerTwo.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.cmbCustomerTwo, 1, 2);
		this.lblCorTypeTwo.setSizeUndefined();
		this.form.addComponent(this.lblCorTypeTwo, 0, 3);
		this.cbxRelationTwo.setSizeUndefined();
		this.form.addComponent(this.cbxRelationTwo, 1, 3);
		this.horizontalLayout.setSizeUndefined();
		this.form.addComponent(this.horizontalLayout, 1, 4);
		this.form.setColumnExpandRatio(1, 100.0F);
		final CustomComponent form_vSpacer = new CustomComponent();
		form_vSpacer.setSizeFull();
		this.form.addComponent(form_vSpacer, 0, 5, 1, 5);
		this.form.setRowExpandRatio(5, 1.0F);
		this.form.setSizeFull();
		this.panel.setContent(this.form);
		this.panel.setSizeFull();
		this.setContent(this.panel);
		this.setSizeFull();

		this.cmdSave.addClickListener(event -> this.cmdSave_buttonClick(event));
		this.cmdReset.addClickListener(event -> this.cmdReset_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel lblCustomerOne, lblCorTypeOne, lblCustomerTwo, lblCorTypeTwo;
	private XdevButton cmdSave, cmdReset;
	private XdevHorizontalLayout horizontalLayout;
	private XdevComboBox<?> cbxRelationOne, cbxRelationTwo;
	private XdevPanel panel;
	private XdevComboBox<Customer> cmbCustomerOne, cmbCustomerTwo;
	private XdevGridLayout form;
	private XdevFieldGroup<ContactRelation> fieldGroup;
	// </generated-code>

}
