package ch.xwr.seicentobilling.ui.desktop.code;

import java.util.Date;

import com.vaadin.event.ShortcutAction;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.xdev.dal.DAOs;
import com.xdev.res.ApplicationResource;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevFieldGroup;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevPanel;
import com.xdev.ui.XdevPopupDateField;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.combobox.XdevComboBox;

import ch.xwr.seicentobilling.business.LovState;
import ch.xwr.seicentobilling.business.RowObjectManager;
import ch.xwr.seicentobilling.dal.VatDAO;
import ch.xwr.seicentobilling.dal.VatLineDAO;
import ch.xwr.seicentobilling.entities.Vat;
import ch.xwr.seicentobilling.entities.VatLine;
import ch.xwr.seicentobilling.entities.VatLine_;
import ch.xwr.seicentobilling.entities.Vat_;

public class VatLinePopup extends XdevView {

	/**
	 *
	 */
	public VatLinePopup() {
		super();
		this.initUI();

		// State
		this.comboBoxState.addItems((Object[]) LovState.State.values());

		// this.comboBoxAccount.addItems((Object[])LovState.Accounts.values());
		// loadDummyCb();

		// get Parameter
		final Long beanId = (Long) UI.getCurrent().getSession().getAttribute("beanId");
		final Long objId = (Long) UI.getCurrent().getSession().getAttribute("objId");
		VatLine bean = null;
		Vat obj = null;

		if (beanId == null) {
			// new
			final VatDAO objDao = new VatDAO();
			obj = objDao.find(objId);

			bean = new VatLine();
			bean.setVanState(LovState.State.active);
			bean.setVanValidFrom(new Date());
			bean.setVat(obj);

		} else {
			final VatLineDAO dao = new VatLineDAO();
			bean = dao.find(beanId.longValue());
		}

		setBeanGui(bean);

	}

	private void setBeanGui(final VatLine bean) {
		// set Bean + Fields
		this.fieldGroup.setItemDataSource(bean);

		// set RO Fields
		setROFields();

		//this.txtExpText.focus();
	}


	private void setROFields() {
//		this.dateExpBooked.setEnabled(false);
//		this.cmbPeriode.setEnabled(false);
	}

	public static Window getPopupWindow() {
		final Window win = new Window();
		win.setWidth("450");
		win.setHeight("390");
		win.center();
		win.setModal(true);
		win.setContent(new VatLinePopup());

		return win;
	}


	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdSave}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_buttonClick(final Button.ClickEvent event) {
		UI.getCurrent().getSession().setAttribute(String.class, "cmdSave");

		try {
			this.fieldGroup.save();
			final RowObjectManager man = new RowObjectManager();
			man.updateObject(this.fieldGroup.getItemDataSource().getBean().getVanId(),
					this.fieldGroup.getItemDataSource().getBean().getClass().getSimpleName());

			((Window) this.getParent()).close();
			Notification.show("Save clicked", "Daten wurden gespeichert", Notification.Type.TRAY_NOTIFICATION);
		} catch (final Exception e) {
			Notification.show("Fehler beim Speichern", e.getMessage(), Notification.Type.ERROR_MESSAGE);
			e.printStackTrace();
		}

	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdReset}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdReset_buttonClick(final Button.ClickEvent event) {
		this.fieldGroup.discard();
		((Window) this.getParent()).close();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.panel = new XdevPanel();
		this.formVan = new XdevGridLayout();
		this.comboBoxState = new XdevComboBox<>();
		this.lblVanValidFrom = new XdevLabel();
		this.dateVanValidFrom = new XdevPopupDateField();
		this.lblVanRate = new XdevLabel();
		this.txtVanRate = new XdevTextField();
		this.lblVanRemark = new XdevLabel();
		this.txtVanRemark = new XdevTextField();
		this.lblVat2 = new XdevLabel();
		this.cmbVat2 = new XdevComboBox<>();
		this.lblVanState = new XdevLabel();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.cmdSave = new XdevButton();
		this.cmdReset = new XdevButton();
		this.fieldGroup = new XdevFieldGroup<>(VatLine.class);

		this.panel.setCaption("MwSt Zeile");
		this.panel.setTabIndex(0);
		this.lblVanValidFrom.setValue("Gültig ab");
		this.lblVanRate.setValue("Ansatz");
		this.lblVanRemark.setValue("Bemerkung");
		this.txtVanRemark.setMaxLength(50);
		this.lblVat2.setValue("Vat");
		this.cmbVat2.setContainerDataSource(Vat.class, DAOs.get(VatDAO.class).findAll());
		this.cmbVat2.setItemCaptionPropertyId(Vat_.vatName.getName());
		this.lblVanState.setValue("State");
		this.horizontalLayout.setMargin(new MarginInfo(false, true, false, true));
		this.cmdSave.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/save1.png"));
		this.cmdSave.setCaption("Speichern");
		this.cmdSave.setClickShortcut(ShortcutAction.KeyCode.ENTER);
		this.cmdReset.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/cancel1.png"));
		this.cmdReset.setCaption("Schliessen");
		this.cmdReset.setClickShortcut(ShortcutAction.KeyCode.ESCAPE);
		this.fieldGroup.bind(this.dateVanValidFrom, VatLine_.vanValidFrom.getName());
		this.fieldGroup.bind(this.txtVanRate, VatLine_.vanRate.getName());
		this.fieldGroup.bind(this.txtVanRemark, VatLine_.vanRemark.getName());
		this.fieldGroup.bind(this.cmbVat2, VatLine_.vat.getName());
		this.fieldGroup.bind(this.comboBoxState, VatLine_.vanState.getName());

		this.cmdSave.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdSave);
		this.horizontalLayout.setComponentAlignment(this.cmdSave, Alignment.MIDDLE_RIGHT);
		this.cmdReset.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdReset);
		this.horizontalLayout.setComponentAlignment(this.cmdReset, Alignment.MIDDLE_RIGHT);
		final CustomComponent horizontalLayout_spacer = new CustomComponent();
		horizontalLayout_spacer.setSizeFull();
		this.horizontalLayout.addComponent(horizontalLayout_spacer);
		this.horizontalLayout.setExpandRatio(horizontalLayout_spacer, 1.0F);
		this.formVan.setColumns(2);
		this.formVan.setRows(7);
		this.comboBoxState.setSizeUndefined();
		this.formVan.addComponent(this.comboBoxState, 1, 4);
		this.lblVanValidFrom.setSizeUndefined();
		this.formVan.addComponent(this.lblVanValidFrom, 0, 0);
		this.dateVanValidFrom.setWidth(100, Unit.PERCENTAGE);
		this.dateVanValidFrom.setHeight(-1, Unit.PIXELS);
		this.formVan.addComponent(this.dateVanValidFrom, 1, 0);
		this.lblVanRate.setSizeUndefined();
		this.formVan.addComponent(this.lblVanRate, 0, 1);
		this.txtVanRate.setWidth(100, Unit.PERCENTAGE);
		this.txtVanRate.setHeight(-1, Unit.PIXELS);
		this.formVan.addComponent(this.txtVanRate, 1, 1);
		this.lblVanRemark.setSizeUndefined();
		this.formVan.addComponent(this.lblVanRemark, 0, 2);
		this.txtVanRemark.setWidth(100, Unit.PERCENTAGE);
		this.txtVanRemark.setHeight(-1, Unit.PIXELS);
		this.formVan.addComponent(this.txtVanRemark, 1, 2);
		this.lblVat2.setSizeUndefined();
		this.formVan.addComponent(this.lblVat2, 0, 3);
		this.cmbVat2.setWidth(100, Unit.PERCENTAGE);
		this.cmbVat2.setHeight(-1, Unit.PIXELS);
		this.formVan.addComponent(this.cmbVat2, 1, 3);
		this.lblVanState.setSizeUndefined();
		this.formVan.addComponent(this.lblVanState, 0, 4);
		this.horizontalLayout.setWidth(100, Unit.PERCENTAGE);
		this.horizontalLayout.setHeight(-1, Unit.PIXELS);
		this.formVan.addComponent(this.horizontalLayout, 0, 5, 1, 5);
		this.formVan.setComponentAlignment(this.horizontalLayout, Alignment.TOP_RIGHT);
		this.formVan.setColumnExpandRatio(1, 20.0F);
		final CustomComponent formVan_vSpacer = new CustomComponent();
		formVan_vSpacer.setSizeFull();
		this.formVan.addComponent(formVan_vSpacer, 0, 6, 1, 6);
		this.formVan.setRowExpandRatio(6, 1.0F);
		this.formVan.setSizeFull();
		this.panel.setContent(this.formVan);
		this.panel.setSizeUndefined();
		this.setContent(this.panel);
		this.setSizeFull();

		this.cmdSave.addClickListener(event -> this.cmdSave_buttonClick(event));
		this.cmdReset.addClickListener(event -> this.cmdReset_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel lblVanValidFrom, lblVanRate, lblVanRemark, lblVat2, lblVanState;
	private XdevButton cmdSave, cmdReset;
	private XdevComboBox<Vat> cmbVat2;
	private XdevHorizontalLayout horizontalLayout;
	private XdevPopupDateField dateVanValidFrom;
	private XdevComboBox<?> comboBoxState;
	private XdevFieldGroup<VatLine> fieldGroup;
	private XdevPanel panel;
	private XdevGridLayout formVan;
	private XdevTextField txtVanRate, txtVanRemark;
	// </generated-code>

}
